version: "0.5"

processes:
  # Backend with hot reload (includes embedded RTSP server)
  backend:
    command: "air"
    availability:
      restart: "on_failure"

  # Frontend dev server
  frontend:
    command: "pnpm dev"
    working_dir: "./ui"
    depends_on:
      backend:
        condition: process_started
    availability:
      restart: "on_failure"
