#!/usr/bin/env node
// Build DTCG tokens into CSS custom properties + TypeScript consts + portable export.
// Zero runtime deps; swap for Style Dictionary v4 later without changing the source format.

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, cpSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(root, "src/design/tokens.dtcg.json");
const OUT_CSS = resolve(root, "src/design/tokens.css");
const OUT_TS = resolve(root, "src/design/tokens.ts");
const EXPORT_DIR = resolve(root, "dist-tokens");
const MODE_EXT = "videonode.mode";

const tokens = JSON.parse(readFileSync(SRC, "utf8"));

const isToken = (n) => n && typeof n === "object" && "$type" in n;
const flatten = (obj, path = []) => {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    const p = [...path, k];
    if (isToken(v)) out.push({ path: p, token: v });
    else if (v && typeof v === "object") out.push(...flatten(v, p));
  }
  return out;
};

const refRe = /^\{([^}]+)\}$/;
const resolveRef = (value) => {
  if (typeof value !== "string") return value;
  const m = refRe.exec(value.trim());
  if (!m) return value;
  const parts = m[1].split(".");
  let node = tokens;
  for (const part of parts) node = node?.[part];
  if (!isToken(node)) throw new Error(`Unresolved token ref: ${m[1]}`);
  // Resolved references are always static (no mode) in the primitive tier.
  return node.$value;
};

const valueFor = (token, mode) => {
  const modeExt = token.$extensions?.[MODE_EXT];
  const raw = modeExt ? modeExt[mode] : token.$value;
  if (raw === undefined) throw new Error(`Missing value for ${mode}`);
  return resolveRef(raw);
};

const utilityName = ({ path }) => `--color-${path.slice(2).join("-")}`; // semantic.color.<name>

const all = flatten(tokens);
const semantic = all.filter(({ path }) => path[0] === "semantic");

const lightDecls = semantic
  .map((t) => `  ${utilityName(t)}: ${valueFor(t.token, "light")};`)
  .join("\n");
const darkDecls = semantic
  .map((t) => `  ${utilityName(t)}: ${valueFor(t.token, "dark")};`)
  .join("\n");

const css = `/* Generated by scripts/build-tokens.mjs — do not edit by hand.
   Source: src/design/tokens.dtcg.json (W3C DTCG 2025.10).
   Declares semantic tokens as Tailwind v4 @theme color utilities (bg-*, text-*, border-*, ring-*).
   The .dark selector swaps values at runtime — components don't need dark: variants for these. */

@theme {
${lightDecls}
}

:where(.dark, .dark *) {
${darkDecls}
}
`;

const tsEntries = semantic
  .map((t) => {
    const key = t.path.slice(2).join("-");
    const light = valueFor(t.token, "light");
    const dark = valueFor(t.token, "dark");
    return `  ${JSON.stringify(key)}: { light: ${JSON.stringify(light)}, dark: ${JSON.stringify(dark)}, cssVar: "var(${utilityName(t)})" }`;
  })
  .join(",\n");

const ts = `// Generated by scripts/build-tokens.mjs — do not edit by hand.
// Source: src/design/tokens.dtcg.json (W3C DTCG 2025.10).
export type TokenEntry = { readonly light: string; readonly dark: string; readonly cssVar: string };

export const semanticTokens = {
${tsEntries}
} as const satisfies Record<string, TokenEntry>;

export type SemanticTokenName = keyof typeof semanticTokens;
`;

mkdirSync(dirname(OUT_CSS), { recursive: true });
writeFileSync(OUT_CSS, css);
writeFileSync(OUT_TS, ts);

mkdirSync(EXPORT_DIR, { recursive: true });
copyFileSync(SRC, resolve(EXPORT_DIR, "videonode-tokens.dtcg.json"));

const tailwindPreset = `// Generated convenience Tailwind preset derived from videonode-tokens.dtcg.json.
// Consumers: \`import preset from './videonode-tokens.tailwind.js'\` and include under theme.extend.
export default {
  theme: {
    extend: {
      colors: {
${semantic
  .map(({ path }) => {
    const name = path.slice(2).join("-");
    return `        [${JSON.stringify(name)}]: "var(--color-${name})"`;
  })
  .join(",\n")}
      }
    }
  }
};
`;
writeFileSync(resolve(EXPORT_DIR, "videonode-tokens.tailwind.js"), tailwindPreset);

// eslint-disable-next-line no-console
console.log(`tokens: wrote ${OUT_CSS.replace(root + "/", "")}, ${OUT_TS.replace(root + "/", "")}, and portable export under ${EXPORT_DIR.replace(root + "/", "")}/`);

// cpSync no-op to keep the import used if future logic needs directory copy.
void cpSync;
