/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description List all available V4L2 video devices
         */
        get: operations["list-devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audio Devices
         * @description List all available audio devices with their capabilities including supported sample rates, formats, and channel configurations
         */
        get: operations["list-audio-devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/format": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Capture Format
         * @description Issue a runtime set_format command to the videonode-source for this device. The source will re-open the V4L2 device with the new format/resolution/fps while keeping all connected consumers attached.
         */
        post: operations["device-set-format"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Formats
         * @description List supported formats for a specific device
         */
        get: operations["device-formats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/framerates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Framerates
         * @description List supported framerates for a specific format and resolution
         */
        get: operations["device-framerates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolutions
         * @description List supported resolutions for a specific format
         */
        get: operations["device-resolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encoders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Encoders
         * @description List validated video and audio encoders available in the system
         */
        get: operations["list-encoders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events Stream
         * @description Real-time event stream for capture results, device changes, and system status
         */
        get: operations["events-stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Check API health status
         */
        get: operations["health-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log Stream
         * @description Real-time log streaming via Server-Sent Events. Sends historical logs first, then streams new logs.
         */
        get: operations["logs-stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Get all Prometheus metrics in JSON format
         */
        get: operations["get-metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get FFmpeg Options
         * @description Get all available FFmpeg options with metadata including descriptions, categories, and conflict information
         */
        get: operations["get-ffmpeg-options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Active Streams
         * @description Get a list of all currently active video streams
         */
        get: operations["list-streams"];
        put?: never;
        /**
         * Create Stream
         * @description Create a new video stream from a device using stable device ID
         */
        post: operations["create-stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/canvas/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Canvas Layout
         * @description Compute the resolved slot + content geometry for a canvas configuration without creating it. The returned layout is the single source of truth for both the ffmpeg composite pipeline and the UI preview.
         */
        post: operations["canvas-layout-preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List live streams
         * @description Returns a list of stream IDs that currently have active producers
         */
        get: operations["list-live-streams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stream
         * @description Get details of a specific stream
         */
        get: operations["get-stream"];
        put?: never;
        post?: never;
        /**
         * Delete Stream
         * @description Delete an active video stream
         */
        delete: operations["delete-stream"];
        options?: never;
        head?: never;
        /**
         * Update Stream
         * @description Partially update an existing video stream with new parameters
         */
        patch: operations["update-stream"];
        trace?: never;
    };
    "/api/streams/{stream_id}/ffmpeg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get FFmpeg Command
         * @description Get the FFmpeg command for a specific stream (either auto-generated or custom)
         */
        get: operations["get-stream-ffmpeg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{stream_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Stream
         * @description Restart a stream process. Stops and restarts the FFmpeg process with current configuration.
         */
        post: operations["restart-stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{stream_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture stream snapshot
         * @description Captures a JPEG snapshot from a running video stream and returns the URL
         */
        post: operations["capture-snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Get application version information
         */
        get: operations["get-version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webrtc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * WebRTC signaling
         * @description Exchange SDP offer/answer for WebRTC streaming
         */
        post: operations["webrtc-offer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AudioDevice: {
            /**
             * @description ALSA device string for FFmpeg
             * @example hw:0,0
             */
            alsa_device: string;
            /**
             * @description Card identifier
             * @example PCH
             */
            card_id: string;
            /**
             * @description Full card name
             * @example HDA Intel PCH
             */
            card_name: string;
            /**
             * Format: int64
             * @description Sound card index
             * @example 0
             */
            card_number: number;
            /**
             * @description Device name
             * @example ALC892 Analog
             */
            device_name: string;
            /**
             * Format: int64
             * @description Device index on card
             * @example 0
             */
            device_number: number;
            /**
             * Format: int64
             * @description Maximum buffer size in frames
             * @example 65536
             */
            max_buffer_size: number;
            /**
             * Format: int64
             * @description Maximum number of channels
             * @example 2
             */
            max_channels: number;
            /**
             * Format: int64
             * @description Maximum period size in frames
             * @example 32768
             */
            max_period_size: number;
            /**
             * Format: int64
             * @description Minimum buffer size in frames
             * @example 64
             */
            min_buffer_size: number;
            /**
             * Format: int64
             * @description Minimum number of channels
             * @example 1
             */
            min_channels: number;
            /**
             * Format: int64
             * @description Minimum period size in frames
             * @example 32
             */
            min_period_size: number;
            /**
             * @description Supported PCM formats
             * @example [
             *       "S16_LE",
             *       "S24_LE"
             *     ]
             */
            supported_formats: string[] | null;
            /**
             * @description Supported sample rates in Hz
             * @example [
             *       44100,
             *       48000,
             *       96000
             *     ]
             */
            supported_rates: number[] | null;
            /**
             * @description Device type: playback, capture, or both
             * @example both
             */
            type: string;
        };
        AudioDevicesData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AudioDevicesData.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of devices found
             * @example 2
             */
            count: number;
            /** @description List of available audio devices */
            devices: components["schemas"]["AudioDevice"][] | null;
        };
        CanvasData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CanvasData.json
             */
            readonly $schema?: string;
            /** @description Standalone ALSA audio devices — one output track per entry */
            audio_devices?: string[] | null;
            /**
             * @description Canvas output framerate
             * @example 30
             */
            fps: string;
            /**
             * Format: int64
             * @description Canvas height — 1080 (1080p), 1440 (1440p), or 2160 (4k)
             * @example 1080
             * @enum {integer}
             */
            height: 1080 | 1440 | 2160;
            /**
             * @description Background color for dead space
             * @example 0x000000
             */
            key_color?: string;
            /** @description Pinned layout candidate name (e.g. "side-by-side", "2x2"). Empty = auto-pick. */
            layout_name?: string;
            /** @description Per-source-stream overrides. When set, length must equal source_streams. Each entry's nil fields inherit from the source stream. */
            source_overrides?: components["schemas"]["CanvasSourceOverrideData"][] | null;
            /** @description Ordered list of source stream IDs (1–4) */
            source_streams: string[] | null;
            /**
             * Format: int64
             * @description Canvas width — 1920 (1080p), 2560 (1440p), or 3840 (4k)
             * @example 1920
             * @enum {integer}
             */
            width: 1920 | 2560 | 3840;
        };
        CanvasLayoutData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CanvasLayoutData.json
             */
            readonly $schema?: string;
            /** @description All candidate layout names available for the current source count, in default-first order */
            available_layouts: string[] | null;
            /** @description Name of the layout candidate actually used */
            chosen_layout: string;
            /** @description One entry per source stream, in the same order as canvas.source_streams */
            slots: components["schemas"]["CanvasLayoutSlotData"][] | null;
        };
        CanvasLayoutSlotData: {
            /**
             * Format: int64
             * @description Content rectangle height
             */
            content_h: number;
            /**
             * Format: int64
             * @description Content rectangle width
             */
            content_w: number;
            /**
             * Format: int64
             * @description Content rectangle X — where the letterboxed input pixels actually land
             */
            content_x: number;
            /**
             * Format: int64
             * @description Content rectangle Y
             */
            content_y: number;
            /**
             * Format: double
             * @description Input aspect ratio after perspective + rotation + crop; 0 when unknown
             */
            effective_aspect_ratio: number;
            /**
             * Format: int64
             * @description Rotation the pipeline applies to this source (after override)
             * @enum {integer}
             */
            rotation_applied: 0 | 90 | 180 | 270;
            /**
             * Format: int64
             * @description Slot rectangle height
             */
            slot_h: number;
            /**
             * Format: int64
             * @description Slot rectangle width
             */
            slot_w: number;
            /**
             * Format: int64
             * @description Slot rectangle X — region allotted by the layout solver
             */
            slot_x: number;
            /**
             * Format: int64
             * @description Slot rectangle Y
             */
            slot_y: number;
            /** @description Source stream ID for this slot */
            source_stream_id: string;
        };
        CanvasRestartedEvent: {
            /** @description Full canvas stream data after restart */
            canvas: components["schemas"]["StreamData"];
            /**
             * @description Canvas stream identifier that was restarted
             * @example mycanvas
             */
            canvas_id: string;
            /**
             * @description Event timestamp
             * @example 2025-01-27T10:30:00Z
             */
            timestamp: string;
            /**
             * @description Source stream whose update triggered the restart
             * @example cam1
             */
            trigger_id: string;
        };
        CanvasSourceOverrideData: {
            /**
             * Format: int64
             * @description Rotation override in degrees; null to inherit from source stream
             * @enum {integer}
             */
            rotation?: 0 | 90 | 180 | 270;
        };
        DeviceCapabilitiesData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeviceCapabilitiesData.json
             */
            readonly $schema?: string;
            /**
             * @description Path to the video device
             * @example /dev/video0
             */
            device_path: string;
            /** @description Supported video formats */
            formats: components["schemas"]["FormatInfo"][] | null;
        };
        DeviceData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeviceData.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of devices found
             * @example 2
             */
            count: number;
            /** @description List of available video devices */
            devices: components["schemas"]["DeviceInfo"][] | null;
        };
        DeviceDiscoveryEvent: {
            /**
             * @description Action type: added, removed, changed
             * @example added
             */
            action: string;
            /**
             * @description Capabilities
             * @example [
             *       "Video Capture",
             *       "Streaming I/O"
             *     ]
             */
            capabilities: string[] | null;
            /**
             * Format: int32
             * @description Raw V4L2 capability flags
             * @example 84000001
             */
            caps: number;
            /**
             * @description Stable device identifier
             * @example usb-0000:00:14.0-1
             */
            device_id: string;
            /**
             * @description Device name
             * @example USB Camera
             */
            device_name: string;
            /**
             * @description System device path
             * @example /dev/video0
             */
            device_path: string;
            /**
             * @description Device ready status
             * @example true
             */
            ready: boolean;
            /**
             * @description Event timestamp
             * @example 2025-01-27T10:30:00Z
             */
            timestamp: string;
            /**
             * Format: int64
             * @description Device type (0=webcam, 1=hdmi, -1=unknown)
             * @example 1
             */
            type: number;
        };
        DeviceFrameratesData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeviceFrameratesData.json
             */
            readonly $schema?: string;
            /** @description Supported framerates */
            framerates: components["schemas"]["Framerate"][] | null;
        };
        DeviceInfo: {
            /**
             * @description Capabilities
             * @example [
             *       "Video Capture",
             *       "Streaming I/O"
             *     ]
             */
            capabilities: string[] | null;
            /**
             * Format: int32
             * @description Raw V4L2 capability flags
             * @example 84000001
             */
            caps: number;
            /**
             * @description Stable device identifier
             * @example usb-0000:00:14.0-1
             */
            device_id: string;
            /**
             * @description Device name
             * @example USB Camera
             */
            device_name: string;
            /**
             * @description System device path
             * @example /dev/video0
             */
            device_path: string;
            /**
             * @description Device ready status
             * @example true
             */
            ready: boolean;
            /**
             * Format: int64
             * @description Device type (0=webcam, 1=hdmi, -1=unknown)
             * @example 1
             */
            type: number;
        };
        DeviceResolutionsData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeviceResolutionsData.json
             */
            readonly $schema?: string;
            /** @description Supported resolutions for the format */
            resolutions: components["schemas"]["Resolution"][] | null;
        };
        DeviceSetFormatBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeviceSetFormatBody.json
             */
            readonly $schema?: string;
            /**
             * @description 4-character V4L2 pixel format code
             * @example YUYV
             */
            fourcc: string;
            /**
             * Format: int32
             * @description Capture framerate; 0 = driver default
             * @example 30
             */
            fps?: number;
            /**
             * Format: int32
             * @description Capture height in pixels
             * @example 1080
             */
            height: number;
            /**
             * Format: int32
             * @description Capture width in pixels
             * @example 1920
             */
            width: number;
        };
        DeviceSetFormatData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeviceSetFormatData.json
             */
            readonly $schema?: string;
            /** @description True if the source accepted and applied the new format */
            applied: boolean;
        };
        EncoderData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EncoderData.json
             */
            readonly $schema?: string;
            /** @description Available audio encoders */
            audio_encoders: components["schemas"]["EncoderInfo"][] | null;
            /**
             * Format: int64
             * @description Total number of encoders
             * @example 15
             */
            count: number;
            /** @description Available video encoders */
            video_encoders: components["schemas"]["EncoderInfo"][] | null;
        };
        EncoderInfo: {
            /**
             * @description Human-readable description
             * @example H.264 encoder
             */
            description: string;
            /**
             * @description Whether this is a hardware-accelerated encoder
             * @example false
             */
            hwaccel: boolean;
            /**
             * @description Encoder name
             * @example libx264
             */
            name: string;
            /**
             * @description Encoder type
             * @example video
             */
            type: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FFmpegCommandData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FFmpegCommandData.json
             */
            readonly $schema?: string;
            /**
             * @description Complete FFmpeg command
             * @example ffmpeg -f v4l2 -i /dev/video0 ...
             */
            command: string;
            /**
             * @description Whether this is a custom command or auto-generated
             * @example false
             */
            is_custom: boolean;
            /**
             * @description Stream identifier
             * @example stream-001
             */
            stream_id: string;
        };
        FormatInfo: {
            /**
             * @description Whether format is emulated
             * @example false
             */
            emulated: boolean;
            /**
             * @description Human-readable format name
             * @example yuyv422
             * @enum {string}
             */
            format_name: "h264" | "yu12" | "yv12" | "nv24" | "nv16" | "mjpeg" | "bgr24" | "rgb24" | "yuyv422" | "nv12";
            /**
             * @description Original V4L2 format name
             * @example YUYV 4:2:2
             */
            original_name: string;
        };
        Framerate: {
            /**
             * Format: int32
             * @description Framerate fraction denominator
             * @example 30
             */
            denominator: number;
            /**
             * Format: double
             * @description Frames per second
             * @example 30
             */
            fps: number;
            /**
             * Format: int32
             * @description Framerate fraction numerator
             * @example 1
             */
            numerator: number;
        };
        HealthData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthData.json
             */
            readonly $schema?: string;
            /**
             * @description Status message
             * @example API is healthy
             */
            message: string;
            /**
             * @description Service status
             * @example ok
             */
            status: string;
        };
        HeartbeatEvent: {
            /** @description Server time at heartbeat */
            timestamp: string;
        };
        LogEntryEvent: {
            /** @description Structured log attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * @description Log level
             * @example info
             */
            level: string;
            /** @description Log message */
            message: string;
            /**
             * @description Source module
             * @example api
             */
            module: string;
            /**
             * @description Log timestamp
             * @example 2025-01-09T10:30:00.123Z
             */
            timestamp: string;
        };
        MetricFamily: {
            help: string;
            metrics: components["schemas"]["MetricValue"][] | null;
            name: string;
            type: string;
        };
        MetricValue: {
            labels?: {
                [key: string]: string;
            };
            /** Format: double */
            value: number;
        };
        Option: {
            app_default: boolean;
            category: string;
            conflicts_with?: string[] | null;
            description: string;
            exclusive_group?: string;
            key: string;
            name: string;
        };
        OptionsData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OptionsData.json
             */
            readonly $schema?: string;
            /** @description All available FFmpeg options with metadata */
            options: components["schemas"]["Option"][] | null;
        };
        PerspectiveData: {
            /** @description Four corner points [[x,y],...] clockwise: top-left, top-right, bottom-right, bottom-left */
            corners: (number[] | null)[] | null;
            /**
             * Format: int64
             * @description Height of the still frame the corners were marked on; used by the GPU compose path to normalize.
             */
            snapshot_height?: number;
            /**
             * Format: int64
             * @description Width of the still frame the corners were marked on; used by the GPU compose path to normalize.
             */
            snapshot_width?: number;
        };
        Resolution: {
            /**
             * Format: int32
             * @description Video height in pixels
             * @example 1080
             */
            height: number;
            /**
             * Format: int32
             * @description Video width in pixels
             * @example 1920
             */
            width: number;
        };
        SnapshotOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SnapshotOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description URL path to the snapshot image
             * @example /api/snapshots/test.jpg
             */
            url: string;
        };
        SourceBroadcastInfo: {
            /** Format: int32 */
            last_seq: number;
            /** Format: int64 */
            placeholder_frames: number;
            /** Format: int64 */
            real_frames: number;
            /** Format: int32 */
            target_fps: number;
        };
        SourceConsumerEntry: {
            /** Format: int64 */
            evicted_at_frame?: number;
            /** Format: int64 */
            fd: number;
            /** Format: int64 */
            frames_dropped: number;
            /** Format: int64 */
            frames_sent: number;
        };
        SourceConsumersInfo: {
            /** Format: int64 */
            count: number;
            evicted: components["schemas"]["SourceConsumerEntry"][] | null;
            live: components["schemas"]["SourceConsumerEntry"][] | null;
        };
        SourceDeviceInfo: {
            multiplanar: boolean;
            path: string;
        };
        SourceFormatInfo: {
            /** Format: int32 */
            buffers: number;
            fourcc: string;
            /** Format: int32 */
            fps: number;
            /** Format: int32 */
            h: number;
            mode: string;
            /** Format: int32 */
            w: number;
        };
        SourceSignalInfo: {
            cable_present: boolean;
            dv_timings: string;
            has_dv_timings: boolean;
            signal_locked: boolean;
        };
        SourceStatusEvent: {
            /** @description Stable device identifier the snapshot describes */
            device_id: string;
            /** @description Full status snapshot from the sidecar */
            status: components["schemas"]["StatusParams"];
            /** @description Server time when received */
            timestamp: string;
        };
        StageStateChangedEvent: {
            /** @description Error message when NewState is 'error' */
            error?: string;
            /** @description New process state */
            new_state: string;
            /** @description Prior process state */
            old_state: string;
            /**
             * Format: int64
             * @description OS pid when running; 0 otherwise
             */
            pid?: number;
            /** @description Pool key, e.g. 'producer:hdmi0' or 'composer:cam-front' */
            stage_id: string;
            /** @description 'producer' | 'composer' | 'encoder' */
            stage_kind: string;
            /** @description User-facing stream this stage belongs to (empty for shared producers) */
            stream_id: string;
            /** @description RFC3339 server time */
            timestamp: string;
        };
        StatusParams: {
            broadcast: components["schemas"]["SourceBroadcastInfo"];
            consumers: components["schemas"]["SourceConsumersInfo"];
            device: components["schemas"]["SourceDeviceInfo"];
            device_id: string;
            format: components["schemas"]["SourceFormatInfo"];
            health: string;
            signal: components["schemas"]["SourceSignalInfo"];
            /** Format: int64 */
            ts_ms: number;
        };
        StreamCreatedEvent: {
            /**
             * @description Action type
             * @example created
             */
            action: string;
            /** @description Created stream data */
            stream: components["schemas"]["StreamData"];
            /**
             * @description Event timestamp
             * @example 2025-01-27T10:30:00Z
             */
            timestamp: string;
        };
        StreamData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StreamData.json
             */
            readonly $schema?: string;
            /**
             * @description ALSA audio device
             * @example hw:4,0
             */
            audio_device?: string;
            /**
             * @description Video bitrate
             * @example 2M
             */
            bitrate?: string;
            /** @description Canvas configuration for composite streams */
            canvas?: components["schemas"]["CanvasData"];
            /**
             * @description Video codec being used
             * @example h264
             */
            codec: string;
            /**
             * @description Custom FFmpeg command override
             * @example ffmpeg -f v4l2...
             */
            custom_ffmpeg_command?: string;
            /**
             * @description Stable device identifier
             * @example usb-0000:00:14.0-1
             */
            device_id: string;
            /**
             * @description Runtime state - device ready and stream active
             * @example true
             */
            enabled: boolean;
            /**
             * @description Video framerate
             * @example 30
             */
            framerate?: string;
            /**
             * @description V4L2 input format
             * @example yuyv422
             */
            input_format?: string;
            /** @description Per-source-stream-ID enabled state (canvas streams only) */
            inputs_enabled?: {
                [key: string]: boolean;
            };
            /** @description Resolved canvas layout (slot + content rects). Populated for canvas streams. */
            layout?: components["schemas"]["CanvasLayoutData"];
            /** @description FFmpeg option keys (e.g., vsync_passthrough, low_latency) */
            options?: string[] | null;
            /** @description Perspective correction corners */
            perspective?: components["schemas"]["PerspectiveData"];
            /**
             * @description Video resolution
             * @example 1920x1080
             */
            resolution?: string;
            /**
             * Format: int64
             * @description Output rotation in degrees (individual streams only)
             * @example 0
             * @enum {integer}
             */
            rotation?: 0 | 90 | 180 | 270;
            /**
             * @description RTSP streaming URL
             * @example rtsp://localhost:8554/stream-001
             */
            rtsp_url?: string;
            /**
             * @description SRT streaming URL
             * @example srt://localhost:6001?streamid=stream-001
             */
            srt_url?: string;
            /**
             * Format: date-time
             * @description When the stream was loaded into memory
             */
            start_time?: string;
            /**
             * @description Unique stream identifier
             * @example stream-001
             */
            stream_id: string;
            /**
             * @description Test pattern mode enabled
             * @example false
             */
            test_mode: boolean;
            /** @description Vision pipeline config */
            vision?: components["schemas"]["VisionData"];
        };
        StreamDeletedEvent: {
            /**
             * @description Action type
             * @example deleted
             */
            action: string;
            /**
             * @description Deleted stream identifier
             * @example stream-001
             */
            stream_id: string;
            /**
             * @description Event timestamp
             * @example 2025-01-27T10:30:00Z
             */
            timestamp: string;
        };
        StreamListData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StreamListData.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of active streams
             * @example 2
             */
            count: number;
            /** @description List of active streams */
            streams: components["schemas"]["StreamData"][] | null;
        };
        StreamListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StreamListOutputBody.json
             */
            readonly $schema?: string;
            /** @description List of active stream IDs */
            streams: string[] | null;
        };
        StreamMetricsEvent: {
            dropped_frames: string;
            duplicate_frames: string;
            fps: string;
            stream_id: string;
            type: string;
        };
        StreamRequestData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StreamRequestData.json
             */
            readonly $schema?: string;
            /**
             * @description ALSA device for audio
             * @example hw:4,0
             */
            audio_device?: string;
            /**
             * Format: double
             * @description Bitrate in Mbps
             * @example 2
             */
            bitrate?: number;
            /** @description Canvas configuration for composite streams referencing 1–4 individual streams */
            canvas?: components["schemas"]["CanvasData"];
            /**
             * @description Video codec standard
             * @example h264
             * @enum {string}
             */
            codec: "h264" | "h265";
            /**
             * @description Stable USB device identifier (required for single-camera streams)
             * @example usb-0000:00:14.0-1
             */
            device_id?: string;
            /**
             * Format: int64
             * @description Video framerate
             * @example 30
             */
            framerate?: number;
            /**
             * Format: int64
             * @description Video height
             * @example 1080
             */
            height?: number;
            /**
             * @description V4L2 input format (required for single-camera streams)
             * @example yuyv422
             */
            input_format?: string;
            /** @description FFmpeg option keys (e.g., vsync_passthrough, low_latency) */
            options?: string[] | null;
            /**
             * Format: int64
             * @description Output rotation in degrees
             * @example 0
             * @enum {integer}
             */
            rotation?: 0 | 90 | 180 | 270;
            /**
             * @description Stream identifier
             * @example my-stream-001
             */
            stream_id: string;
            /**
             * Format: int64
             * @description Video width
             * @example 1920
             */
            width?: number;
        };
        StreamStateChangedEvent: {
            /**
             * @description Action: enabled, disabled, running
             * @example running
             */
            action?: string;
            /**
             * @description Whether stream is enabled
             * @example true
             */
            enabled: boolean;
            /**
             * @description Stream identifier
             * @example stream-001
             */
            stream_id: string;
            /**
             * @description Event timestamp
             * @example 2025-01-27T10:30:00Z
             */
            timestamp: string;
        };
        StreamUpdateRequestData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StreamUpdateRequestData.json
             */
            readonly $schema?: string;
            /**
             * @description ALSA device for audio
             * @example hw:4,0
             */
            audio_device?: string;
            /**
             * Format: double
             * @description Bitrate in Mbps
             * @example 2
             */
            bitrate?: number;
            /** @description Canvas configuration for composite streams (replaces entire canvas) */
            canvas?: components["schemas"]["CanvasData"];
            /**
             * @description Video codec standard
             * @example h264
             * @enum {string}
             */
            codec?: "h264" | "h265";
            /**
             * @description Custom FFmpeg command override
             * @example ffmpeg -f v4l2...
             */
            custom_ffmpeg_command?: string;
            /**
             * @description Manual override of runtime enabled state
             * @example true
             */
            enabled?: boolean;
            /**
             * Format: int64
             * @description Video framerate
             * @example 30
             */
            framerate?: number;
            /**
             * Format: int64
             * @description Video height
             * @example 1080
             */
            height?: number;
            /**
             * @description V4L2 input format
             * @example yuyv422
             */
            input_format?: string;
            /** @description FFmpeg option keys (e.g., vsync_passthrough, low_latency) */
            options?: string[] | null;
            /** @description Perspective corners (null to clear) */
            perspective?: components["schemas"]["PerspectiveData"] | null;
            /**
             * Format: int64
             * @description Output rotation in degrees
             * @example 0
             * @enum {integer}
             */
            rotation?: 0 | 90 | 180 | 270;
            /**
             * @description Enable test pattern mode instead of device capture
             * @example false
             */
            test_mode?: boolean;
            /** @description Vision config (null to clear) */
            vision?: components["schemas"]["VisionData"] | null;
            /**
             * Format: int64
             * @description Video width
             * @example 1920
             */
            width?: number;
        };
        StreamUpdatedEvent: {
            /**
             * @description Action type
             * @example updated
             */
            action: string;
            /** @description Updated stream data */
            stream: components["schemas"]["StreamData"];
            /**
             * @description Event timestamp
             * @example 2025-01-27T10:30:00Z
             */
            timestamp: string;
        };
        VersionData: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/VersionData.json
             */
            readonly $schema?: string;
            /**
             * @description Build timestamp
             * @example 2024-12-15 14:30
             */
            build_date: string;
            /**
             * @description Unique build identifier
             * @example a1b2c3d4
             */
            build_id: string;
            /**
             * @description Compiler used
             * @example gc
             */
            compiler: string;
            /**
             * @description Git commit SHA
             * @example abc1234
             */
            git_commit: string;
            /**
             * @description Go compiler version
             * @example go1.21.0
             */
            go_version: string;
            /**
             * @description Platform
             * @example linux/amd64
             */
            platform: string;
            /**
             * @description Application version
             * @example dev
             */
            version: string;
        };
        VisionData: {
            /** @description Enable raw frame output for AI pipeline */
            enabled: boolean;
            /**
             * Format: int64
             * @description Vision pipe frame rate (1-60). 0 = use server default.
             */
            fps?: number;
            /**
             * Format: int64
             * @description Raw frame height (default 480)
             */
            height?: number;
            /**
             * Format: int64
             * @description Raw frame width (default 640)
             */
            width?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-audio-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioDevicesData"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "device-set-format": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable device identifier */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceSetFormatBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSetFormatData"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "device-formats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable device identifier */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCapabilitiesData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "device-framerates": {
        parameters: {
            query?: {
                /** @description Human-readable format name */
                format_name?: "yv12" | "nv24" | "nv16" | "mjpeg" | "bgr24" | "rgb24" | "yuyv422" | "nv12" | "h264" | "yu12";
                /** @description Video width in pixels */
                width?: number;
                /** @description Video height in pixels */
                height?: number;
            };
            header?: never;
            path: {
                /** @description Stable device identifier */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceFrameratesData"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "device-resolutions": {
        parameters: {
            query?: {
                /** @description Human-readable format name */
                format_name?: "yuyv422" | "nv12" | "h264" | "yu12" | "yv12" | "nv24" | "nv16" | "mjpeg" | "bgr24" | "rgb24";
            };
            header?: never;
            path: {
                /** @description Stable device identifier */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResolutionsData"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-encoders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncoderData"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "events-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["CanvasRestartedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "canvas-restarted";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["DeviceDiscoveryEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "device-discovery";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["HeartbeatEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "heartbeat";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["SourceStatusEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "source-status";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["StageStateChangedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "stage-state-changed";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["StreamCreatedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "stream-created";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["StreamDeletedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "stream-deleted";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["StreamMetricsEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "stream-metrics";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["StreamStateChangedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "stream-state-changed";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["StreamUpdatedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "stream-updated";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthData"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "logs-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        data: components["schemas"]["LogEntryEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event?: "message";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricFamily"][] | null;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-ffmpeg-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamListData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamRequestData"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamData"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "canvas-layout-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasData"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasLayoutData"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-live-streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier */
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier */
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier */
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamUpdateRequestData"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamData"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-stream-ffmpeg": {
        parameters: {
            query?: {
                /** @description Override the auto-selected encoder */
                override?: string;
            };
            header?: never;
            path: {
                /** @description Stream identifier */
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FFmpegCommandData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "restart-stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier */
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "capture-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream ID to capture snapshot from */
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOutputBody"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionData"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "webrtc-offer": {
        parameters: {
            query: {
                /** @description Stream ID to connect to */
                stream: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/sdp": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
