// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: control/common.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NativeInfo replaces the legacy `identify` JSON-RPC notification.
// Returned by every native binary's Describe() unary RPC. The daemon
// calls Describe() immediately after dialing the per-binary UDS so it
// can record the running PID + version and verify identity.
type NativeInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Pid      uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Version  string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// "source" or "composer". Empty defaults to "source" for back-compat
	// with the legacy identify payload.
	Kind string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// Bump when adding required fields. Receivers tolerate higher minor
	// versions but reject incompatible majors.
	ProtocolVersion uint32 `protobuf:"varint,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NativeInfo) Reset() {
	*x = NativeInfo{}
	mi := &file_control_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeInfo) ProtoMessage() {}

func (x *NativeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeInfo.ProtoReflect.Descriptor instead.
func (*NativeInfo) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{0}
}

func (x *NativeInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *NativeInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NativeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NativeInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NativeInfo) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Multiplanar   bool                   `protobuf:"varint,2,opt,name=multiplanar,proto3" json:"multiplanar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_control_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeviceInfo) GetMultiplanar() bool {
	if x != nil {
		return x.Multiplanar
	}
	return false
}

type SignalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasDvTimings  bool                   `protobuf:"varint,1,opt,name=has_dv_timings,json=hasDvTimings,proto3" json:"has_dv_timings,omitempty"`
	CablePresent  bool                   `protobuf:"varint,2,opt,name=cable_present,json=cablePresent,proto3" json:"cable_present,omitempty"`
	SignalLocked  bool                   `protobuf:"varint,3,opt,name=signal_locked,json=signalLocked,proto3" json:"signal_locked,omitempty"`
	DvTimings     string                 `protobuf:"bytes,4,opt,name=dv_timings,json=dvTimings,proto3" json:"dv_timings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalInfo) Reset() {
	*x = SignalInfo{}
	mi := &file_control_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalInfo) ProtoMessage() {}

func (x *SignalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalInfo.ProtoReflect.Descriptor instead.
func (*SignalInfo) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{2}
}

func (x *SignalInfo) GetHasDvTimings() bool {
	if x != nil {
		return x.HasDvTimings
	}
	return false
}

func (x *SignalInfo) GetCablePresent() bool {
	if x != nil {
		return x.CablePresent
	}
	return false
}

func (x *SignalInfo) GetSignalLocked() bool {
	if x != nil {
		return x.SignalLocked
	}
	return false
}

func (x *SignalInfo) GetDvTimings() string {
	if x != nil {
		return x.DvTimings
	}
	return ""
}

type FormatInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Fourcc  string                 `protobuf:"bytes,1,opt,name=fourcc,proto3" json:"fourcc,omitempty"`
	W       uint32                 `protobuf:"varint,2,opt,name=w,proto3" json:"w,omitempty"`
	H       uint32                 `protobuf:"varint,3,opt,name=h,proto3" json:"h,omitempty"`
	Fps     uint32                 `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	Buffers uint32                 `protobuf:"varint,5,opt,name=buffers,proto3" json:"buffers,omitempty"`
	// "rga" | "mjpeg-mpp" | "mjpeg-turbojpeg"
	Mode string `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	// Detected YCbCr matrix: "bt601" | "bt709".
	ColorMatrix   string `protobuf:"bytes,7,opt,name=color_matrix,json=colorMatrix,proto3" json:"color_matrix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatInfo) Reset() {
	*x = FormatInfo{}
	mi := &file_control_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatInfo) ProtoMessage() {}

func (x *FormatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatInfo.ProtoReflect.Descriptor instead.
func (*FormatInfo) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{3}
}

func (x *FormatInfo) GetFourcc() string {
	if x != nil {
		return x.Fourcc
	}
	return ""
}

func (x *FormatInfo) GetW() uint32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *FormatInfo) GetH() uint32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *FormatInfo) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *FormatInfo) GetBuffers() uint32 {
	if x != nil {
		return x.Buffers
	}
	return 0
}

func (x *FormatInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FormatInfo) GetColorMatrix() string {
	if x != nil {
		return x.ColorMatrix
	}
	return ""
}

type BroadcastInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetFps         uint32                 `protobuf:"varint,1,opt,name=target_fps,json=targetFps,proto3" json:"target_fps,omitempty"`
	RealFrames        uint64                 `protobuf:"varint,2,opt,name=real_frames,json=realFrames,proto3" json:"real_frames,omitempty"`
	PlaceholderFrames uint64                 `protobuf:"varint,3,opt,name=placeholder_frames,json=placeholderFrames,proto3" json:"placeholder_frames,omitempty"`
	LastSeq           uint32                 `protobuf:"varint,4,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BroadcastInfo) Reset() {
	*x = BroadcastInfo{}
	mi := &file_control_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastInfo) ProtoMessage() {}

func (x *BroadcastInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastInfo.ProtoReflect.Descriptor instead.
func (*BroadcastInfo) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastInfo) GetTargetFps() uint32 {
	if x != nil {
		return x.TargetFps
	}
	return 0
}

func (x *BroadcastInfo) GetRealFrames() uint64 {
	if x != nil {
		return x.RealFrames
	}
	return 0
}

func (x *BroadcastInfo) GetPlaceholderFrames() uint64 {
	if x != nil {
		return x.PlaceholderFrames
	}
	return 0
}

func (x *BroadcastInfo) GetLastSeq() uint32 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type ConsumerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	FramesSent    uint64                 `protobuf:"varint,2,opt,name=frames_sent,json=framesSent,proto3" json:"frames_sent,omitempty"`
	FramesDropped uint64                 `protobuf:"varint,3,opt,name=frames_dropped,json=framesDropped,proto3" json:"frames_dropped,omitempty"`
	// Only set on entries in the `evicted` list.
	EvictedAtFrame uint64 `protobuf:"varint,4,opt,name=evicted_at_frame,json=evictedAtFrame,proto3" json:"evicted_at_frame,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumerEntry) Reset() {
	*x = ConsumerEntry{}
	mi := &file_control_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerEntry) ProtoMessage() {}

func (x *ConsumerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerEntry.ProtoReflect.Descriptor instead.
func (*ConsumerEntry) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumerEntry) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *ConsumerEntry) GetFramesSent() uint64 {
	if x != nil {
		return x.FramesSent
	}
	return 0
}

func (x *ConsumerEntry) GetFramesDropped() uint64 {
	if x != nil {
		return x.FramesDropped
	}
	return 0
}

func (x *ConsumerEntry) GetEvictedAtFrame() uint64 {
	if x != nil {
		return x.EvictedAtFrame
	}
	return 0
}

type ConsumersInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Live          []*ConsumerEntry       `protobuf:"bytes,2,rep,name=live,proto3" json:"live,omitempty"`
	Evicted       []*ConsumerEntry       `protobuf:"bytes,3,rep,name=evicted,proto3" json:"evicted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumersInfo) Reset() {
	*x = ConsumersInfo{}
	mi := &file_control_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumersInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumersInfo) ProtoMessage() {}

func (x *ConsumersInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumersInfo.ProtoReflect.Descriptor instead.
func (*ConsumersInfo) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumersInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ConsumersInfo) GetLive() []*ConsumerEntry {
	if x != nil {
		return x.Live
	}
	return nil
}

func (x *ConsumersInfo) GetEvicted() []*ConsumerEntry {
	if x != nil {
		return x.Evicted
	}
	return nil
}

type Status struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TsMs     int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	// Source liveness token (videonode-source/source_probe::health_token):
	// "live" | "transitioning" | "no_cable" | "no_signal" | "initializing" | "offline"
	Health        string         `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	Device        *DeviceInfo    `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Signal        *SignalInfo    `protobuf:"bytes,5,opt,name=signal,proto3" json:"signal,omitempty"`
	Format        *FormatInfo    `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Broadcast     *BroadcastInfo `protobuf:"bytes,7,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Consumers     *ConsumersInfo `protobuf:"bytes,8,opt,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_control_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_control_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_control_common_proto_rawDescGZIP(), []int{7}
}

func (x *Status) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Status) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *Status) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *Status) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *Status) GetSignal() *SignalInfo {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *Status) GetFormat() *FormatInfo {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *Status) GetBroadcast() *BroadcastInfo {
	if x != nil {
		return x.Broadcast
	}
	return nil
}

func (x *Status) GetConsumers() *ConsumersInfo {
	if x != nil {
		return x.Consumers
	}
	return nil
}

var File_control_common_proto protoreflect.FileDescriptor

const file_control_common_proto_rawDesc = "" +
	"\n" +
	"\x14control/common.proto\x12\x11videonode.control\"\x94\x01\n" +
	"\n" +
	"NativeInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\rR\x0fprotocolVersion\"B\n" +
	"\n" +
	"DeviceInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12 \n" +
	"\vmultiplanar\x18\x02 \x01(\bR\vmultiplanar\"\x9b\x01\n" +
	"\n" +
	"SignalInfo\x12$\n" +
	"\x0ehas_dv_timings\x18\x01 \x01(\bR\fhasDvTimings\x12#\n" +
	"\rcable_present\x18\x02 \x01(\bR\fcablePresent\x12#\n" +
	"\rsignal_locked\x18\x03 \x01(\bR\fsignalLocked\x12\x1d\n" +
	"\n" +
	"dv_timings\x18\x04 \x01(\tR\tdvTimings\"\xa3\x01\n" +
	"\n" +
	"FormatInfo\x12\x16\n" +
	"\x06fourcc\x18\x01 \x01(\tR\x06fourcc\x12\f\n" +
	"\x01w\x18\x02 \x01(\rR\x01w\x12\f\n" +
	"\x01h\x18\x03 \x01(\rR\x01h\x12\x10\n" +
	"\x03fps\x18\x04 \x01(\rR\x03fps\x12\x18\n" +
	"\abuffers\x18\x05 \x01(\rR\abuffers\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12!\n" +
	"\fcolor_matrix\x18\a \x01(\tR\vcolorMatrix\"\x99\x01\n" +
	"\rBroadcastInfo\x12\x1d\n" +
	"\n" +
	"target_fps\x18\x01 \x01(\rR\ttargetFps\x12\x1f\n" +
	"\vreal_frames\x18\x02 \x01(\x04R\n" +
	"realFrames\x12-\n" +
	"\x12placeholder_frames\x18\x03 \x01(\x04R\x11placeholderFrames\x12\x19\n" +
	"\blast_seq\x18\x04 \x01(\rR\alastSeq\"\x91\x01\n" +
	"\rConsumerEntry\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x1f\n" +
	"\vframes_sent\x18\x02 \x01(\x04R\n" +
	"framesSent\x12%\n" +
	"\x0eframes_dropped\x18\x03 \x01(\x04R\rframesDropped\x12(\n" +
	"\x10evicted_at_frame\x18\x04 \x01(\x04R\x0eevictedAtFrame\"\x97\x01\n" +
	"\rConsumersInfo\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x124\n" +
	"\x04live\x18\x02 \x03(\v2 .videonode.control.ConsumerEntryR\x04live\x12:\n" +
	"\aevicted\x18\x03 \x03(\v2 .videonode.control.ConsumerEntryR\aevicted\"\xf7\x02\n" +
	"\x06Status\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\x12\x16\n" +
	"\x06health\x18\x03 \x01(\tR\x06health\x125\n" +
	"\x06device\x18\x04 \x01(\v2\x1d.videonode.control.DeviceInfoR\x06device\x125\n" +
	"\x06signal\x18\x05 \x01(\v2\x1d.videonode.control.SignalInfoR\x06signal\x125\n" +
	"\x06format\x18\x06 \x01(\v2\x1d.videonode.control.FormatInfoR\x06format\x12>\n" +
	"\tbroadcast\x18\a \x01(\v2 .videonode.control.BroadcastInfoR\tbroadcast\x12>\n" +
	"\tconsumers\x18\b \x01(\v2 .videonode.control.ConsumersInfoR\tconsumersBIZGgithub.com/smazurov/videonode/internal/streams/pipelinectl/pb;controlpbb\x06proto3"

var (
	file_control_common_proto_rawDescOnce sync.Once
	file_control_common_proto_rawDescData []byte
)

func file_control_common_proto_rawDescGZIP() []byte {
	file_control_common_proto_rawDescOnce.Do(func() {
		file_control_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_common_proto_rawDesc), len(file_control_common_proto_rawDesc)))
	})
	return file_control_common_proto_rawDescData
}

var file_control_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_control_common_proto_goTypes = []any{
	(*NativeInfo)(nil),    // 0: videonode.control.NativeInfo
	(*DeviceInfo)(nil),    // 1: videonode.control.DeviceInfo
	(*SignalInfo)(nil),    // 2: videonode.control.SignalInfo
	(*FormatInfo)(nil),    // 3: videonode.control.FormatInfo
	(*BroadcastInfo)(nil), // 4: videonode.control.BroadcastInfo
	(*ConsumerEntry)(nil), // 5: videonode.control.ConsumerEntry
	(*ConsumersInfo)(nil), // 6: videonode.control.ConsumersInfo
	(*Status)(nil),        // 7: videonode.control.Status
}
var file_control_common_proto_depIdxs = []int32{
	5, // 0: videonode.control.ConsumersInfo.live:type_name -> videonode.control.ConsumerEntry
	5, // 1: videonode.control.ConsumersInfo.evicted:type_name -> videonode.control.ConsumerEntry
	1, // 2: videonode.control.Status.device:type_name -> videonode.control.DeviceInfo
	2, // 3: videonode.control.Status.signal:type_name -> videonode.control.SignalInfo
	3, // 4: videonode.control.Status.format:type_name -> videonode.control.FormatInfo
	4, // 5: videonode.control.Status.broadcast:type_name -> videonode.control.BroadcastInfo
	6, // 6: videonode.control.Status.consumers:type_name -> videonode.control.ConsumersInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_control_common_proto_init() }
func file_control_common_proto_init() {
	if File_control_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_common_proto_rawDesc), len(file_control_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_common_proto_goTypes,
		DependencyIndexes: file_control_common_proto_depIdxs,
		MessageInfos:      file_control_common_proto_msgTypes,
	}.Build()
	File_control_common_proto = out.File
	file_control_common_proto_goTypes = nil
	file_control_common_proto_depIdxs = nil
}
