// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: control/composer.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Composer_Describe_FullMethodName       = "/videonode.control.Composer/Describe"
	Composer_SetCanvas_FullMethodName      = "/videonode.control.Composer/SetCanvas"
	Composer_SetSource_FullMethodName      = "/videonode.control.Composer/SetSource"
	Composer_ClearSource_FullMethodName    = "/videonode.control.Composer/ClearSource"
	Composer_SetLayout_FullMethodName      = "/videonode.control.Composer/SetLayout"
	Composer_SetEffects_FullMethodName     = "/videonode.control.Composer/SetEffects"
	Composer_SetSourceState_FullMethodName = "/videonode.control.Composer/SetSourceState"
	Composer_GetStats_FullMethodName       = "/videonode.control.Composer/GetStats"
	Composer_Snapshot_FullMethodName       = "/videonode.control.Composer/Snapshot"
	Composer_Shutdown_FullMethodName       = "/videonode.control.Composer/Shutdown"
)

// ComposerClient is the client API for Composer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Composer is the gRPC service exposed by every videonode-composer
// binary over its per-instance Unix-domain socket. Composer is fully
// daemon-driven: argv is just --drm-device / --grpc-listen / --composer-id.
// Everything else (canvas dims, slot bindings, layout, effects,
// per-source state) arrives over this RPC surface.
//
// Composers do not push status today; if/when they do, add
// StreamStatus here mirroring source.proto.
type ComposerClient interface {
	// Describe returns the composer's identity. First call after dial.
	Describe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NativeInfo, error)
	// SetCanvas configures the output canvas. Must arrive before the
	// composer can render anything useful.
	SetCanvas(ctx context.Context, in *SetCanvasRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SetSource binds a slot to a SCM-publishing source.
	SetSource(ctx context.Context, in *SetSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ClearSource unbinds a slot.
	ClearSource(ctx context.Context, in *ClearSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SetLayout atomically replaces the composer's placement set.
	SetLayout(ctx context.Context, in *SetLayoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SetEffects atomically replaces the effect list bound to source_id.
	SetEffects(ctx context.Context, in *SetEffectsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SetSourceState notifies the composer that a source's collapsed
	// health state changed. Composer applies the user warp only when
	// state is "live" or "transitioning".
	SetSourceState(ctx context.Context, in *SetSourceStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetStats returns a point-in-time snapshot of the render loop's
	// counters: frames rendered, observed fps (last ~1s window), the
	// current canvas dimensions, and the SCM consumer count. Cheap;
	// intended for periodic polling by the daemon. Process uptime lives
	// in the Go process supervisor and is not duplicated here.
	GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ComposerStats, error)
	// Snapshot captures one rendered frame from the canvas loop and
	// returns the raw NV12 bytes plus dimensions (symmetric with
	// Source.Snapshot). Cost is on-demand (mmap + memcpy out of the NV12
	// broadcast buffer on the gRPC thread), not per produced frame.
	Snapshot(ctx context.Context, in *ComposerSnapshotRequest, opts ...grpc.CallOption) (*ComposerSnapshotResponse, error)
	// Shutdown asks the composer to exit cleanly.
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type composerClient struct {
	cc grpc.ClientConnInterface
}

func NewComposerClient(cc grpc.ClientConnInterface) ComposerClient {
	return &composerClient{cc}
}

func (c *composerClient) Describe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NativeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NativeInfo)
	err := c.cc.Invoke(ctx, Composer_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) SetCanvas(ctx context.Context, in *SetCanvasRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Composer_SetCanvas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) SetSource(ctx context.Context, in *SetSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Composer_SetSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) ClearSource(ctx context.Context, in *ClearSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Composer_ClearSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) SetLayout(ctx context.Context, in *SetLayoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Composer_SetLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) SetEffects(ctx context.Context, in *SetEffectsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Composer_SetEffects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) SetSourceState(ctx context.Context, in *SetSourceStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Composer_SetSourceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ComposerStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComposerStats)
	err := c.cc.Invoke(ctx, Composer_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) Snapshot(ctx context.Context, in *ComposerSnapshotRequest, opts ...grpc.CallOption) (*ComposerSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComposerSnapshotResponse)
	err := c.cc.Invoke(ctx, Composer_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composerClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Composer_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComposerServer is the server API for Composer service.
// All implementations must embed UnimplementedComposerServer
// for forward compatibility.
//
// Composer is the gRPC service exposed by every videonode-composer
// binary over its per-instance Unix-domain socket. Composer is fully
// daemon-driven: argv is just --drm-device / --grpc-listen / --composer-id.
// Everything else (canvas dims, slot bindings, layout, effects,
// per-source state) arrives over this RPC surface.
//
// Composers do not push status today; if/when they do, add
// StreamStatus here mirroring source.proto.
type ComposerServer interface {
	// Describe returns the composer's identity. First call after dial.
	Describe(context.Context, *emptypb.Empty) (*NativeInfo, error)
	// SetCanvas configures the output canvas. Must arrive before the
	// composer can render anything useful.
	SetCanvas(context.Context, *SetCanvasRequest) (*emptypb.Empty, error)
	// SetSource binds a slot to a SCM-publishing source.
	SetSource(context.Context, *SetSourceRequest) (*emptypb.Empty, error)
	// ClearSource unbinds a slot.
	ClearSource(context.Context, *ClearSourceRequest) (*emptypb.Empty, error)
	// SetLayout atomically replaces the composer's placement set.
	SetLayout(context.Context, *SetLayoutRequest) (*emptypb.Empty, error)
	// SetEffects atomically replaces the effect list bound to source_id.
	SetEffects(context.Context, *SetEffectsRequest) (*emptypb.Empty, error)
	// SetSourceState notifies the composer that a source's collapsed
	// health state changed. Composer applies the user warp only when
	// state is "live" or "transitioning".
	SetSourceState(context.Context, *SetSourceStateRequest) (*emptypb.Empty, error)
	// GetStats returns a point-in-time snapshot of the render loop's
	// counters: frames rendered, observed fps (last ~1s window), the
	// current canvas dimensions, and the SCM consumer count. Cheap;
	// intended for periodic polling by the daemon. Process uptime lives
	// in the Go process supervisor and is not duplicated here.
	GetStats(context.Context, *emptypb.Empty) (*ComposerStats, error)
	// Snapshot captures one rendered frame from the canvas loop and
	// returns the raw NV12 bytes plus dimensions (symmetric with
	// Source.Snapshot). Cost is on-demand (mmap + memcpy out of the NV12
	// broadcast buffer on the gRPC thread), not per produced frame.
	Snapshot(context.Context, *ComposerSnapshotRequest) (*ComposerSnapshotResponse, error)
	// Shutdown asks the composer to exit cleanly.
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedComposerServer()
}

// UnimplementedComposerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComposerServer struct{}

func (UnimplementedComposerServer) Describe(context.Context, *emptypb.Empty) (*NativeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedComposerServer) SetCanvas(context.Context, *SetCanvasRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCanvas not implemented")
}
func (UnimplementedComposerServer) SetSource(context.Context, *SetSourceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSource not implemented")
}
func (UnimplementedComposerServer) ClearSource(context.Context, *ClearSourceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearSource not implemented")
}
func (UnimplementedComposerServer) SetLayout(context.Context, *SetLayoutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLayout not implemented")
}
func (UnimplementedComposerServer) SetEffects(context.Context, *SetEffectsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEffects not implemented")
}
func (UnimplementedComposerServer) SetSourceState(context.Context, *SetSourceStateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSourceState not implemented")
}
func (UnimplementedComposerServer) GetStats(context.Context, *emptypb.Empty) (*ComposerStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedComposerServer) Snapshot(context.Context, *ComposerSnapshotRequest) (*ComposerSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedComposerServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedComposerServer) mustEmbedUnimplementedComposerServer() {}
func (UnimplementedComposerServer) testEmbeddedByValue()                  {}

// UnsafeComposerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComposerServer will
// result in compilation errors.
type UnsafeComposerServer interface {
	mustEmbedUnimplementedComposerServer()
}

func RegisterComposerServer(s grpc.ServiceRegistrar, srv ComposerServer) {
	// If the following call panics, it indicates UnimplementedComposerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Composer_ServiceDesc, srv)
}

func _Composer_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).Describe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_SetCanvas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCanvasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).SetCanvas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_SetCanvas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).SetCanvas(ctx, req.(*SetCanvasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_SetSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).SetSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_SetSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).SetSource(ctx, req.(*SetSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_ClearSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).ClearSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_ClearSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).ClearSource(ctx, req.(*ClearSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_SetLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).SetLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_SetLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).SetLayout(ctx, req.(*SetLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_SetEffects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEffectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).SetEffects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_SetEffects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).SetEffects(ctx, req.(*SetEffectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_SetSourceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSourceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).SetSourceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_SetSourceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).SetSourceState(ctx, req.(*SetSourceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).GetStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComposerSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).Snapshot(ctx, req.(*ComposerSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Composer_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposerServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Composer_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposerServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Composer_ServiceDesc is the grpc.ServiceDesc for Composer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Composer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videonode.control.Composer",
	HandlerType: (*ComposerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Composer_Describe_Handler,
		},
		{
			MethodName: "SetCanvas",
			Handler:    _Composer_SetCanvas_Handler,
		},
		{
			MethodName: "SetSource",
			Handler:    _Composer_SetSource_Handler,
		},
		{
			MethodName: "ClearSource",
			Handler:    _Composer_ClearSource_Handler,
		},
		{
			MethodName: "SetLayout",
			Handler:    _Composer_SetLayout_Handler,
		},
		{
			MethodName: "SetEffects",
			Handler:    _Composer_SetEffects_Handler,
		},
		{
			MethodName: "SetSourceState",
			Handler:    _Composer_SetSourceState_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Composer_GetStats_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Composer_Snapshot_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Composer_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control/composer.proto",
}
