// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: control/composer.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComposerStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total frames the canvas loop has produced since the process started,
	// including the pre-ready solid-black frames. Monotonically increasing.
	FramesRendered uint64 `protobuf:"varint,1,opt,name=frames_rendered,json=framesRendered,proto3" json:"frames_rendered,omitempty"`
	// Frames observed in the most recent ~1s sampling window. 0 until the
	// first window closes.
	FpsObserved float64 `protobuf:"fixed64,2,opt,name=fps_observed,json=fpsObserved,proto3" json:"fps_observed,omitempty"`
	// Current canvas dimensions; 0 before the first SetCanvas + ready snapshot.
	CanvasW   uint32 `protobuf:"varint,3,opt,name=canvas_w,json=canvasW,proto3" json:"canvas_w,omitempty"`
	CanvasH   uint32 `protobuf:"varint,4,opt,name=canvas_h,json=canvasH,proto3" json:"canvas_h,omitempty"`
	CanvasFps uint32 `protobuf:"varint,5,opt,name=canvas_fps,json=canvasFps,proto3" json:"canvas_fps,omitempty"`
	// SCM consumer count. Always 0 in stdout-output mode.
	ConsumerCount int32 `protobuf:"varint,6,opt,name=consumer_count,json=consumerCount,proto3" json:"consumer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposerStats) Reset() {
	*x = ComposerStats{}
	mi := &file_control_composer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposerStats) ProtoMessage() {}

func (x *ComposerStats) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposerStats.ProtoReflect.Descriptor instead.
func (*ComposerStats) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{0}
}

func (x *ComposerStats) GetFramesRendered() uint64 {
	if x != nil {
		return x.FramesRendered
	}
	return 0
}

func (x *ComposerStats) GetFpsObserved() float64 {
	if x != nil {
		return x.FpsObserved
	}
	return 0
}

func (x *ComposerStats) GetCanvasW() uint32 {
	if x != nil {
		return x.CanvasW
	}
	return 0
}

func (x *ComposerStats) GetCanvasH() uint32 {
	if x != nil {
		return x.CanvasH
	}
	return 0
}

func (x *ComposerStats) GetCanvasFps() uint32 {
	if x != nil {
		return x.CanvasFps
	}
	return 0
}

func (x *ComposerStats) GetConsumerCount() int32 {
	if x != nil {
		return x.ConsumerCount
	}
	return 0
}

type SetCanvasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             uint32                 `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	H             uint32                 `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	Fps           uint32                 `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCanvasRequest) Reset() {
	*x = SetCanvasRequest{}
	mi := &file_control_composer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCanvasRequest) ProtoMessage() {}

func (x *SetCanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCanvasRequest.ProtoReflect.Descriptor instead.
func (*SetCanvasRequest) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{1}
}

func (x *SetCanvasRequest) GetW() uint32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *SetCanvasRequest) GetH() uint32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *SetCanvasRequest) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

type SetSourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// free-form slot identifier ("a", "b", ...)
	Slot string `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// stable source identifier (matches the source's own --device-id)
	SourceId string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Unix-socket path where the source's scm_rights_producer is listening
	ScmPath       string `protobuf:"bytes,3,opt,name=scm_path,json=scmPath,proto3" json:"scm_path,omitempty"`
	Width         uint32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Fps           uint32 `protobuf:"varint,6,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSourceRequest) Reset() {
	*x = SetSourceRequest{}
	mi := &file_control_composer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSourceRequest) ProtoMessage() {}

func (x *SetSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSourceRequest.ProtoReflect.Descriptor instead.
func (*SetSourceRequest) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{2}
}

func (x *SetSourceRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *SetSourceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SetSourceRequest) GetScmPath() string {
	if x != nil {
		return x.ScmPath
	}
	return ""
}

func (x *SetSourceRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SetSourceRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SetSourceRequest) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

type ClearSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSourceRequest) Reset() {
	*x = ClearSourceRequest{}
	mi := &file_control_composer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSourceRequest) ProtoMessage() {}

func (x *ClearSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSourceRequest.ProtoReflect.Descriptor instead.
func (*ClearSourceRequest) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{3}
}

func (x *ClearSourceRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type LayoutSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slot  string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// canvas pixel coordinates; x/y may be negative (clipped off-canvas).
	X             int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	W             int32 `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	H             int32 `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayoutSlot) Reset() {
	*x = LayoutSlot{}
	mi := &file_control_composer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayoutSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutSlot) ProtoMessage() {}

func (x *LayoutSlot) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutSlot.ProtoReflect.Descriptor instead.
func (*LayoutSlot) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{4}
}

func (x *LayoutSlot) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *LayoutSlot) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LayoutSlot) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LayoutSlot) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *LayoutSlot) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type SetLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*LayoutSlot          `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLayoutRequest) Reset() {
	*x = SetLayoutRequest{}
	mi := &file_control_composer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLayoutRequest) ProtoMessage() {}

func (x *SetLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLayoutRequest.ProtoReflect.Descriptor instead.
func (*SetLayoutRequest) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{5}
}

func (x *SetLayoutRequest) GetSlots() []*LayoutSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// PerspectiveEffectParams holds an integer-pixel quadrilateral plus the
// snapshot dimensions used to normalize corners to UV [0,1].
type PerspectiveEffectParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TLx, TLy, TRx, TRy, BRx, BRy, BLx, BLy — exactly 8 ints, order fixed.
	Corners       []int32 `protobuf:"varint,1,rep,packed,name=corners,proto3" json:"corners,omitempty"`
	SnapshotW     int32   `protobuf:"varint,2,opt,name=snapshot_w,json=snapshotW,proto3" json:"snapshot_w,omitempty"`
	SnapshotH     int32   `protobuf:"varint,3,opt,name=snapshot_h,json=snapshotH,proto3" json:"snapshot_h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerspectiveEffectParams) Reset() {
	*x = PerspectiveEffectParams{}
	mi := &file_control_composer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerspectiveEffectParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerspectiveEffectParams) ProtoMessage() {}

func (x *PerspectiveEffectParams) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerspectiveEffectParams.ProtoReflect.Descriptor instead.
func (*PerspectiveEffectParams) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{6}
}

func (x *PerspectiveEffectParams) GetCorners() []int32 {
	if x != nil {
		return x.Corners
	}
	return nil
}

func (x *PerspectiveEffectParams) GetSnapshotW() int32 {
	if x != nil {
		return x.SnapshotW
	}
	return 0
}

func (x *PerspectiveEffectParams) GetSnapshotH() int32 {
	if x != nil {
		return x.SnapshotH
	}
	return 0
}

type Effect struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "perspective" (others reserved). Unknown types are logged + skipped.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Populated iff type == "perspective".
	Perspective   *PerspectiveEffectParams `protobuf:"bytes,2,opt,name=perspective,proto3" json:"perspective,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_control_composer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{7}
}

func (x *Effect) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Effect) GetPerspective() *PerspectiveEffectParams {
	if x != nil {
		return x.Perspective
	}
	return nil
}

type SetEffectsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SourceId string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// order-significant; composer applies in array order.
	Effects       []*Effect `protobuf:"bytes,2,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEffectsRequest) Reset() {
	*x = SetEffectsRequest{}
	mi := &file_control_composer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEffectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEffectsRequest) ProtoMessage() {}

func (x *SetEffectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEffectsRequest.ProtoReflect.Descriptor instead.
func (*SetEffectsRequest) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{8}
}

func (x *SetEffectsRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SetEffectsRequest) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

type SetSourceStateRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SourceId string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// "live" | "transitioning" | "placeholder"
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSourceStateRequest) Reset() {
	*x = SetSourceStateRequest{}
	mi := &file_control_composer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSourceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSourceStateRequest) ProtoMessage() {}

func (x *SetSourceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_composer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSourceStateRequest.ProtoReflect.Descriptor instead.
func (*SetSourceStateRequest) Descriptor() ([]byte, []int) {
	return file_control_composer_proto_rawDescGZIP(), []int{9}
}

func (x *SetSourceStateRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SetSourceStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_control_composer_proto protoreflect.FileDescriptor

const file_control_composer_proto_rawDesc = "" +
	"\n" +
	"\x16control/composer.proto\x12\x11videonode.control\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14control/common.proto\"\xd7\x01\n" +
	"\rComposerStats\x12'\n" +
	"\x0fframes_rendered\x18\x01 \x01(\x04R\x0eframesRendered\x12!\n" +
	"\ffps_observed\x18\x02 \x01(\x01R\vfpsObserved\x12\x19\n" +
	"\bcanvas_w\x18\x03 \x01(\rR\acanvasW\x12\x19\n" +
	"\bcanvas_h\x18\x04 \x01(\rR\acanvasH\x12\x1d\n" +
	"\n" +
	"canvas_fps\x18\x05 \x01(\rR\tcanvasFps\x12%\n" +
	"\x0econsumer_count\x18\x06 \x01(\x05R\rconsumerCount\"@\n" +
	"\x10SetCanvasRequest\x12\f\n" +
	"\x01w\x18\x01 \x01(\rR\x01w\x12\f\n" +
	"\x01h\x18\x02 \x01(\rR\x01h\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\rR\x03fps\"\x9e\x01\n" +
	"\x10SetSourceRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x19\n" +
	"\bscm_path\x18\x03 \x01(\tR\ascmPath\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x06 \x01(\rR\x03fps\"(\n" +
	"\x12ClearSourceRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"X\n" +
	"\n" +
	"LayoutSlot\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x04 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x05 \x01(\x05R\x01h\"G\n" +
	"\x10SetLayoutRequest\x123\n" +
	"\x05slots\x18\x01 \x03(\v2\x1d.videonode.control.LayoutSlotR\x05slots\"q\n" +
	"\x17PerspectiveEffectParams\x12\x18\n" +
	"\acorners\x18\x01 \x03(\x05R\acorners\x12\x1d\n" +
	"\n" +
	"snapshot_w\x18\x02 \x01(\x05R\tsnapshotW\x12\x1d\n" +
	"\n" +
	"snapshot_h\x18\x03 \x01(\x05R\tsnapshotH\"j\n" +
	"\x06Effect\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12L\n" +
	"\vperspective\x18\x02 \x01(\v2*.videonode.control.PerspectiveEffectParamsR\vperspective\"e\n" +
	"\x11SetEffectsRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x123\n" +
	"\aeffects\x18\x02 \x03(\v2\x19.videonode.control.EffectR\aeffects\"J\n" +
	"\x15SetSourceStateRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state2\x9b\x05\n" +
	"\bComposer\x12A\n" +
	"\bDescribe\x12\x16.google.protobuf.Empty\x1a\x1d.videonode.control.NativeInfo\x12H\n" +
	"\tSetCanvas\x12#.videonode.control.SetCanvasRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\tSetSource\x12#.videonode.control.SetSourceRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vClearSource\x12%.videonode.control.ClearSourceRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\tSetLayout\x12#.videonode.control.SetLayoutRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\n" +
	"SetEffects\x12$.videonode.control.SetEffectsRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0eSetSourceState\x12(.videonode.control.SetSourceStateRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a .videonode.control.ComposerStats\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBIZGgithub.com/smazurov/videonode/internal/streams/pipelinectl/pb;controlpbb\x06proto3"

var (
	file_control_composer_proto_rawDescOnce sync.Once
	file_control_composer_proto_rawDescData []byte
)

func file_control_composer_proto_rawDescGZIP() []byte {
	file_control_composer_proto_rawDescOnce.Do(func() {
		file_control_composer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_composer_proto_rawDesc), len(file_control_composer_proto_rawDesc)))
	})
	return file_control_composer_proto_rawDescData
}

var file_control_composer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_control_composer_proto_goTypes = []any{
	(*ComposerStats)(nil),           // 0: videonode.control.ComposerStats
	(*SetCanvasRequest)(nil),        // 1: videonode.control.SetCanvasRequest
	(*SetSourceRequest)(nil),        // 2: videonode.control.SetSourceRequest
	(*ClearSourceRequest)(nil),      // 3: videonode.control.ClearSourceRequest
	(*LayoutSlot)(nil),              // 4: videonode.control.LayoutSlot
	(*SetLayoutRequest)(nil),        // 5: videonode.control.SetLayoutRequest
	(*PerspectiveEffectParams)(nil), // 6: videonode.control.PerspectiveEffectParams
	(*Effect)(nil),                  // 7: videonode.control.Effect
	(*SetEffectsRequest)(nil),       // 8: videonode.control.SetEffectsRequest
	(*SetSourceStateRequest)(nil),   // 9: videonode.control.SetSourceStateRequest
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
	(*NativeInfo)(nil),              // 11: videonode.control.NativeInfo
}
var file_control_composer_proto_depIdxs = []int32{
	4,  // 0: videonode.control.SetLayoutRequest.slots:type_name -> videonode.control.LayoutSlot
	6,  // 1: videonode.control.Effect.perspective:type_name -> videonode.control.PerspectiveEffectParams
	7,  // 2: videonode.control.SetEffectsRequest.effects:type_name -> videonode.control.Effect
	10, // 3: videonode.control.Composer.Describe:input_type -> google.protobuf.Empty
	1,  // 4: videonode.control.Composer.SetCanvas:input_type -> videonode.control.SetCanvasRequest
	2,  // 5: videonode.control.Composer.SetSource:input_type -> videonode.control.SetSourceRequest
	3,  // 6: videonode.control.Composer.ClearSource:input_type -> videonode.control.ClearSourceRequest
	5,  // 7: videonode.control.Composer.SetLayout:input_type -> videonode.control.SetLayoutRequest
	8,  // 8: videonode.control.Composer.SetEffects:input_type -> videonode.control.SetEffectsRequest
	9,  // 9: videonode.control.Composer.SetSourceState:input_type -> videonode.control.SetSourceStateRequest
	10, // 10: videonode.control.Composer.GetStats:input_type -> google.protobuf.Empty
	10, // 11: videonode.control.Composer.Shutdown:input_type -> google.protobuf.Empty
	11, // 12: videonode.control.Composer.Describe:output_type -> videonode.control.NativeInfo
	10, // 13: videonode.control.Composer.SetCanvas:output_type -> google.protobuf.Empty
	10, // 14: videonode.control.Composer.SetSource:output_type -> google.protobuf.Empty
	10, // 15: videonode.control.Composer.ClearSource:output_type -> google.protobuf.Empty
	10, // 16: videonode.control.Composer.SetLayout:output_type -> google.protobuf.Empty
	10, // 17: videonode.control.Composer.SetEffects:output_type -> google.protobuf.Empty
	10, // 18: videonode.control.Composer.SetSourceState:output_type -> google.protobuf.Empty
	0,  // 19: videonode.control.Composer.GetStats:output_type -> videonode.control.ComposerStats
	10, // 20: videonode.control.Composer.Shutdown:output_type -> google.protobuf.Empty
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_control_composer_proto_init() }
func file_control_composer_proto_init() {
	if File_control_composer_proto != nil {
		return
	}
	file_control_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_composer_proto_rawDesc), len(file_control_composer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_composer_proto_goTypes,
		DependencyIndexes: file_control_composer_proto_depIdxs,
		MessageInfos:      file_control_composer_proto_msgTypes,
	}.Build()
	File_control_composer_proto = out.File
	file_control_composer_proto_goTypes = nil
	file_control_composer_proto_depIdxs = nil
}
