// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: control/sensor.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SensorInfo is the capability handshake. `native` reuses the common
// identity (pid/version/kind="sensor"); the rest lets the daemon verify
// the wire schema and know which payload kinds this sensor can emit.
type SensorInfo struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Native *NativeInfo            `protobuf:"bytes,1,opt,name=native,proto3" json:"native,omitempty"`
	// Bump when the Finding wire shape changes incompatibly.
	SchemaVersion uint32 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Opaque id of the active detector + weights (e.g. "playfield-classical-v0",
	// "playfield-rknn-v3"). Stamped onto every Finding for per-model eval.
	ModelId string `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Payload kinds this sensor emits: "bbox" | "quad" | "polygon" | ...
	Kinds         []string `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorInfo) Reset() {
	*x = SensorInfo{}
	mi := &file_control_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorInfo) ProtoMessage() {}

func (x *SensorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorInfo.ProtoReflect.Descriptor instead.
func (*SensorInfo) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorInfo) GetNative() *NativeInfo {
	if x != nil {
		return x.Native
	}
	return nil
}

func (x *SensorInfo) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *SensorInfo) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SensorInfo) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Upstream the sensor observes, e.g. "source:cam". Stamped onto Findings.
	TargetRef string `protobuf:"bytes,1,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	// "propose" (emit candidates for operator confirm) | "auto" (apply directly).
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// Opaque detector params (boost amount, thresholds, margin, min/max area,
	// tick interval). Struct so new knobs never need a proto bump.
	Params        *structpb.Struct `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_control_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureRequest) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *ConfigureRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ConfigureRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_control_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{2}
}

type StreamFindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFindingsRequest) Reset() {
	*x = StreamFindingsRequest{}
	mi := &file_control_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFindingsRequest) ProtoMessage() {}

func (x *StreamFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFindingsRequest.ProtoReflect.Descriptor instead.
func (*StreamFindingsRequest) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{3}
}

// Finding is the unit of perception. The envelope (fields 1-7) is stable; the
// payload oneof (16+) is the additive growth point; `extra` is an opaque
// never-load-bearing side channel.
type Finding struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SensorId string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	// Detector/weights that produced this (echoes SensorInfo.model_id).
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Upstream this pertains to, e.g. "source:cam".
	TargetRef string `protobuf:"bytes,3,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	FrameIdx  uint64 `protobuf:"varint,4,opt,name=frame_idx,json=frameIdx,proto3" json:"frame_idx,omitempty"`
	// CLOCK_MONOTONIC nanoseconds at capture.
	CapturedAtNs  int64   `protobuf:"varint,5,opt,name=captured_at_ns,json=capturedAtNs,proto3" json:"captured_at_ns,omitempty"`
	Confidence    float32 `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SchemaVersion uint32  `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Finding_Bbox
	//	*Finding_Quad
	//	*Finding_Polygon
	//	*Finding_Mask
	//	*Finding_Keypoints
	//	*Finding_Label
	Payload isFinding_Payload `protobuf_oneof:"payload"`
	// Opaque hints (e.g. {"sample_hint": true} when the detector was unsure).
	// The daemon may read it for policy; it is never required for correctness.
	Extra         *structpb.Struct `protobuf:"bytes,31,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_control_sensor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *Finding) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Finding) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *Finding) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *Finding) GetFrameIdx() uint64 {
	if x != nil {
		return x.FrameIdx
	}
	return 0
}

func (x *Finding) GetCapturedAtNs() int64 {
	if x != nil {
		return x.CapturedAtNs
	}
	return 0
}

func (x *Finding) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Finding) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Finding) GetPayload() isFinding_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Finding) GetBbox() *BBox {
	if x != nil {
		if x, ok := x.Payload.(*Finding_Bbox); ok {
			return x.Bbox
		}
	}
	return nil
}

func (x *Finding) GetQuad() *Quad {
	if x != nil {
		if x, ok := x.Payload.(*Finding_Quad); ok {
			return x.Quad
		}
	}
	return nil
}

func (x *Finding) GetPolygon() *Polygon {
	if x != nil {
		if x, ok := x.Payload.(*Finding_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

func (x *Finding) GetMask() *Mask {
	if x != nil {
		if x, ok := x.Payload.(*Finding_Mask); ok {
			return x.Mask
		}
	}
	return nil
}

func (x *Finding) GetKeypoints() *Keypoints {
	if x != nil {
		if x, ok := x.Payload.(*Finding_Keypoints); ok {
			return x.Keypoints
		}
	}
	return nil
}

func (x *Finding) GetLabel() *Label {
	if x != nil {
		if x, ok := x.Payload.(*Finding_Label); ok {
			return x.Label
		}
	}
	return nil
}

func (x *Finding) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type isFinding_Payload interface {
	isFinding_Payload()
}

type Finding_Bbox struct {
	Bbox *BBox `protobuf:"bytes,16,opt,name=bbox,proto3,oneof"`
}

type Finding_Quad struct {
	Quad *Quad `protobuf:"bytes,17,opt,name=quad,proto3,oneof"`
}

type Finding_Polygon struct {
	Polygon *Polygon `protobuf:"bytes,18,opt,name=polygon,proto3,oneof"`
}

type Finding_Mask struct {
	Mask *Mask `protobuf:"bytes,19,opt,name=mask,proto3,oneof"`
}

type Finding_Keypoints struct {
	Keypoints *Keypoints `protobuf:"bytes,20,opt,name=keypoints,proto3,oneof"`
}

type Finding_Label struct {
	Label *Label `protobuf:"bytes,21,opt,name=label,proto3,oneof"`
}

func (*Finding_Bbox) isFinding_Payload() {}

func (*Finding_Quad) isFinding_Payload() {}

func (*Finding_Polygon) isFinding_Payload() {}

func (*Finding_Mask) isFinding_Payload() {}

func (*Finding_Keypoints) isFinding_Payload() {}

func (*Finding_Label) isFinding_Payload() {}

// BBox is an axis-aligned rectangle: top-left (x,y) + size (w,h).
type BBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	W             float32                `protobuf:"fixed32,3,opt,name=w,proto3" json:"w,omitempty"`
	H             float32                `protobuf:"fixed32,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BBox) Reset() {
	*x = BBox{}
	mi := &file_control_sensor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{5}
}

func (x *BBox) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BBox) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BBox) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BBox) GetH() float32 {
	if x != nil {
		return x.H
	}
	return 0
}

// Quad is exactly 8 floats: TL.x,TL.y,TR.x,TR.y,BR.x,BR.y,BL.x,BL.y.
type Quad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xy            []float32              `protobuf:"fixed32,1,rep,packed,name=xy,proto3" json:"xy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quad) Reset() {
	*x = Quad{}
	mi := &file_control_sensor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quad) ProtoMessage() {}

func (x *Quad) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quad.ProtoReflect.Descriptor instead.
func (*Quad) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{6}
}

func (x *Quad) GetXy() []float32 {
	if x != nil {
		return x.Xy
	}
	return nil
}

// Polygon is an arbitrary closed ring of (x,y) pairs (even length).
type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xy            []float32              `protobuf:"fixed32,1,rep,packed,name=xy,proto3" json:"xy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_control_sensor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{7}
}

func (x *Polygon) GetXy() []float32 {
	if x != nil {
		return x.Xy
	}
	return nil
}

// Mask is a binary/region mask. `data` is row-major; interpretation
// (raw bits vs RLE) is carried in Finding.extra until a kind needs more.
type Mask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mask) Reset() {
	*x = Mask{}
	mi := &file_control_sensor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mask) ProtoMessage() {}

func (x *Mask) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mask.ProtoReflect.Descriptor instead.
func (*Mask) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{8}
}

func (x *Mask) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Mask) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Mask) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Keypoints: parallel arrays of normalized (x,y) pairs and per-point score.
type Keypoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xy            []float32              `protobuf:"fixed32,1,rep,packed,name=xy,proto3" json:"xy,omitempty"`
	Score         []float32              `protobuf:"fixed32,2,rep,packed,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keypoints) Reset() {
	*x = Keypoints{}
	mi := &file_control_sensor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keypoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keypoints) ProtoMessage() {}

func (x *Keypoints) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keypoints.ProtoReflect.Descriptor instead.
func (*Keypoints) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{9}
}

func (x *Keypoints) GetXy() []float32 {
	if x != nil {
		return x.Xy
	}
	return nil
}

func (x *Keypoints) GetScore() []float32 {
	if x != nil {
		return x.Score
	}
	return nil
}

// Label is a classification result; geometry-free.
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_control_sensor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_control_sensor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_control_sensor_proto_rawDescGZIP(), []int{10}
}

func (x *Label) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_control_sensor_proto protoreflect.FileDescriptor

const file_control_sensor_proto_rawDesc = "" +
	"\n" +
	"\x14control/sensor.proto\x12\x11videonode.control\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14control/common.proto\"\x9b\x01\n" +
	"\n" +
	"SensorInfo\x125\n" +
	"\x06native\x18\x01 \x01(\v2\x1d.videonode.control.NativeInfoR\x06native\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x14\n" +
	"\x05kinds\x18\x04 \x03(\tR\x05kinds\"v\n" +
	"\x10ConfigureRequest\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x01 \x01(\tR\ttargetRef\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\"\x10\n" +
	"\x0eAnalyzeRequest\"\x17\n" +
	"\x15StreamFindingsRequest\"\xd9\x04\n" +
	"\aFinding\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x03 \x01(\tR\ttargetRef\x12\x1b\n" +
	"\tframe_idx\x18\x04 \x01(\x04R\bframeIdx\x12$\n" +
	"\x0ecaptured_at_ns\x18\x05 \x01(\x03R\fcapturedAtNs\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x12%\n" +
	"\x0eschema_version\x18\a \x01(\rR\rschemaVersion\x12-\n" +
	"\x04bbox\x18\x10 \x01(\v2\x17.videonode.control.BBoxH\x00R\x04bbox\x12-\n" +
	"\x04quad\x18\x11 \x01(\v2\x17.videonode.control.QuadH\x00R\x04quad\x126\n" +
	"\apolygon\x18\x12 \x01(\v2\x1a.videonode.control.PolygonH\x00R\apolygon\x12-\n" +
	"\x04mask\x18\x13 \x01(\v2\x17.videonode.control.MaskH\x00R\x04mask\x12<\n" +
	"\tkeypoints\x18\x14 \x01(\v2\x1c.videonode.control.KeypointsH\x00R\tkeypoints\x120\n" +
	"\x05label\x18\x15 \x01(\v2\x18.videonode.control.LabelH\x00R\x05label\x12-\n" +
	"\x05extra\x18\x1f \x01(\v2\x17.google.protobuf.StructR\x05extraB\t\n" +
	"\apayload\">\n" +
	"\x04BBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x02R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x02R\x01h\"\x16\n" +
	"\x04Quad\x12\x0e\n" +
	"\x02xy\x18\x01 \x03(\x02R\x02xy\"\x19\n" +
	"\aPolygon\x12\x0e\n" +
	"\x02xy\x18\x01 \x03(\x02R\x02xy\"H\n" +
	"\x04Mask\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"1\n" +
	"\tKeypoints\x12\x0e\n" +
	"\x02xy\x18\x01 \x03(\x02R\x02xy\x12\x14\n" +
	"\x05score\x18\x02 \x03(\x02R\x05score\"\x1b\n" +
	"\x05Label\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\xf9\x02\n" +
	"\x06Sensor\x12A\n" +
	"\bDescribe\x12\x16.google.protobuf.Empty\x1a\x1d.videonode.control.SensorInfo\x12H\n" +
	"\tConfigure\x12#.videonode.control.ConfigureRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vAnalyzeOnce\x12!.videonode.control.AnalyzeRequest\x1a\x1a.videonode.control.Finding\x12X\n" +
	"\x0eStreamFindings\x12(.videonode.control.StreamFindingsRequest\x1a\x1a.videonode.control.Finding0\x01\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBIZGgithub.com/smazurov/videonode/internal/streams/pipelinectl/pb;controlpbb\x06proto3"

var (
	file_control_sensor_proto_rawDescOnce sync.Once
	file_control_sensor_proto_rawDescData []byte
)

func file_control_sensor_proto_rawDescGZIP() []byte {
	file_control_sensor_proto_rawDescOnce.Do(func() {
		file_control_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_sensor_proto_rawDesc), len(file_control_sensor_proto_rawDesc)))
	})
	return file_control_sensor_proto_rawDescData
}

var file_control_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_control_sensor_proto_goTypes = []any{
	(*SensorInfo)(nil),            // 0: videonode.control.SensorInfo
	(*ConfigureRequest)(nil),      // 1: videonode.control.ConfigureRequest
	(*AnalyzeRequest)(nil),        // 2: videonode.control.AnalyzeRequest
	(*StreamFindingsRequest)(nil), // 3: videonode.control.StreamFindingsRequest
	(*Finding)(nil),               // 4: videonode.control.Finding
	(*BBox)(nil),                  // 5: videonode.control.BBox
	(*Quad)(nil),                  // 6: videonode.control.Quad
	(*Polygon)(nil),               // 7: videonode.control.Polygon
	(*Mask)(nil),                  // 8: videonode.control.Mask
	(*Keypoints)(nil),             // 9: videonode.control.Keypoints
	(*Label)(nil),                 // 10: videonode.control.Label
	(*NativeInfo)(nil),            // 11: videonode.control.NativeInfo
	(*structpb.Struct)(nil),       // 12: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_control_sensor_proto_depIdxs = []int32{
	11, // 0: videonode.control.SensorInfo.native:type_name -> videonode.control.NativeInfo
	12, // 1: videonode.control.ConfigureRequest.params:type_name -> google.protobuf.Struct
	5,  // 2: videonode.control.Finding.bbox:type_name -> videonode.control.BBox
	6,  // 3: videonode.control.Finding.quad:type_name -> videonode.control.Quad
	7,  // 4: videonode.control.Finding.polygon:type_name -> videonode.control.Polygon
	8,  // 5: videonode.control.Finding.mask:type_name -> videonode.control.Mask
	9,  // 6: videonode.control.Finding.keypoints:type_name -> videonode.control.Keypoints
	10, // 7: videonode.control.Finding.label:type_name -> videonode.control.Label
	12, // 8: videonode.control.Finding.extra:type_name -> google.protobuf.Struct
	13, // 9: videonode.control.Sensor.Describe:input_type -> google.protobuf.Empty
	1,  // 10: videonode.control.Sensor.Configure:input_type -> videonode.control.ConfigureRequest
	2,  // 11: videonode.control.Sensor.AnalyzeOnce:input_type -> videonode.control.AnalyzeRequest
	3,  // 12: videonode.control.Sensor.StreamFindings:input_type -> videonode.control.StreamFindingsRequest
	13, // 13: videonode.control.Sensor.Shutdown:input_type -> google.protobuf.Empty
	0,  // 14: videonode.control.Sensor.Describe:output_type -> videonode.control.SensorInfo
	13, // 15: videonode.control.Sensor.Configure:output_type -> google.protobuf.Empty
	4,  // 16: videonode.control.Sensor.AnalyzeOnce:output_type -> videonode.control.Finding
	4,  // 17: videonode.control.Sensor.StreamFindings:output_type -> videonode.control.Finding
	13, // 18: videonode.control.Sensor.Shutdown:output_type -> google.protobuf.Empty
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_control_sensor_proto_init() }
func file_control_sensor_proto_init() {
	if File_control_sensor_proto != nil {
		return
	}
	file_control_common_proto_init()
	file_control_sensor_proto_msgTypes[4].OneofWrappers = []any{
		(*Finding_Bbox)(nil),
		(*Finding_Quad)(nil),
		(*Finding_Polygon)(nil),
		(*Finding_Mask)(nil),
		(*Finding_Keypoints)(nil),
		(*Finding_Label)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_sensor_proto_rawDesc), len(file_control_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_sensor_proto_goTypes,
		DependencyIndexes: file_control_sensor_proto_depIdxs,
		MessageInfos:      file_control_sensor_proto_msgTypes,
	}.Build()
	File_control_sensor_proto = out.File
	file_control_sensor_proto_goTypes = nil
	file_control_sensor_proto_depIdxs = nil
}
