// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: control/sensor.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sensor_Describe_FullMethodName       = "/videonode.control.Sensor/Describe"
	Sensor_Configure_FullMethodName      = "/videonode.control.Sensor/Configure"
	Sensor_AnalyzeOnce_FullMethodName    = "/videonode.control.Sensor/AnalyzeOnce"
	Sensor_StreamFindings_FullMethodName = "/videonode.control.Sensor/StreamFindings"
	Sensor_Shutdown_FullMethodName       = "/videonode.control.Sensor/Shutdown"
)

// SensorClient is the client API for Sensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sensor is the gRPC service exposed by every videonode-sensor binary
// over its per-instance Unix-domain socket (path passed via --grpc-listen).
// The daemon dials in, calls Describe() to record identity + capabilities,
// Configure()s the detector, then subscribes to StreamFindings for the
// continuous perception push (mirrors Source.StreamStatus).
//
// The contract is PERCEPTION-ONLY: it carries observations, never actions.
// Mapping a Finding to a pipeline action (crop, perspective, framing) is the
// daemon's job, keyed by where the operator attached the sensor. All
// geometry is in NORMALIZED [0,1] coordinates so it is resolution- and
// snapshot-independent. The Finding envelope is stable; new perception kinds
// are added as `oneof payload` variants — an additive, backward-compatible
// protobuf change (old clients ignore the unknown field number).
type SensorClient interface {
	// Describe returns identity + capabilities. First call after dial.
	Describe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SensorInfo, error)
	// Configure (re)points the detector: which upstream it observes, the
	// propose/auto mode, and opaque detector params. Idempotent; may be
	// called again to retune without a restart.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AnalyzeOnce runs the detector on the latest frame and returns a single
	// Finding. For on-demand calibration / probes; the continuous push is
	// StreamFindings below.
	AnalyzeOnce(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*Finding, error)
	// StreamFindings yields a Finding per detection at the sensor's
	// (periodic) tick rate. The stream stays open for the process lifetime.
	StreamFindings(ctx context.Context, in *StreamFindingsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Finding], error)
	// Shutdown asks the sensor to exit cleanly.
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sensorClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorClient(cc grpc.ClientConnInterface) SensorClient {
	return &sensorClient{cc}
}

func (c *sensorClient) Describe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SensorInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorInfo)
	err := c.cc.Invoke(ctx, Sensor_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Sensor_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorClient) AnalyzeOnce(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*Finding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Finding)
	err := c.cc.Invoke(ctx, Sensor_AnalyzeOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorClient) StreamFindings(ctx context.Context, in *StreamFindingsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Finding], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sensor_ServiceDesc.Streams[0], Sensor_StreamFindings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFindingsRequest, Finding]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sensor_StreamFindingsClient = grpc.ServerStreamingClient[Finding]

func (c *sensorClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Sensor_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServer is the server API for Sensor service.
// All implementations must embed UnimplementedSensorServer
// for forward compatibility.
//
// Sensor is the gRPC service exposed by every videonode-sensor binary
// over its per-instance Unix-domain socket (path passed via --grpc-listen).
// The daemon dials in, calls Describe() to record identity + capabilities,
// Configure()s the detector, then subscribes to StreamFindings for the
// continuous perception push (mirrors Source.StreamStatus).
//
// The contract is PERCEPTION-ONLY: it carries observations, never actions.
// Mapping a Finding to a pipeline action (crop, perspective, framing) is the
// daemon's job, keyed by where the operator attached the sensor. All
// geometry is in NORMALIZED [0,1] coordinates so it is resolution- and
// snapshot-independent. The Finding envelope is stable; new perception kinds
// are added as `oneof payload` variants — an additive, backward-compatible
// protobuf change (old clients ignore the unknown field number).
type SensorServer interface {
	// Describe returns identity + capabilities. First call after dial.
	Describe(context.Context, *emptypb.Empty) (*SensorInfo, error)
	// Configure (re)points the detector: which upstream it observes, the
	// propose/auto mode, and opaque detector params. Idempotent; may be
	// called again to retune without a restart.
	Configure(context.Context, *ConfigureRequest) (*emptypb.Empty, error)
	// AnalyzeOnce runs the detector on the latest frame and returns a single
	// Finding. For on-demand calibration / probes; the continuous push is
	// StreamFindings below.
	AnalyzeOnce(context.Context, *AnalyzeRequest) (*Finding, error)
	// StreamFindings yields a Finding per detection at the sensor's
	// (periodic) tick rate. The stream stays open for the process lifetime.
	StreamFindings(*StreamFindingsRequest, grpc.ServerStreamingServer[Finding]) error
	// Shutdown asks the sensor to exit cleanly.
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedSensorServer()
}

// UnimplementedSensorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorServer struct{}

func (UnimplementedSensorServer) Describe(context.Context, *emptypb.Empty) (*SensorInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedSensorServer) Configure(context.Context, *ConfigureRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedSensorServer) AnalyzeOnce(context.Context, *AnalyzeRequest) (*Finding, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeOnce not implemented")
}
func (UnimplementedSensorServer) StreamFindings(*StreamFindingsRequest, grpc.ServerStreamingServer[Finding]) error {
	return status.Error(codes.Unimplemented, "method StreamFindings not implemented")
}
func (UnimplementedSensorServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedSensorServer) mustEmbedUnimplementedSensorServer() {}
func (UnimplementedSensorServer) testEmbeddedByValue()                {}

// UnsafeSensorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServer will
// result in compilation errors.
type UnsafeSensorServer interface {
	mustEmbedUnimplementedSensorServer()
}

func RegisterSensorServer(s grpc.ServiceRegistrar, srv SensorServer) {
	// If the following call panics, it indicates UnimplementedSensorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sensor_ServiceDesc, srv)
}

func _Sensor_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sensor_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServer).Describe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sensor_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sensor_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sensor_AnalyzeOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServer).AnalyzeOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sensor_AnalyzeOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServer).AnalyzeOnce(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sensor_StreamFindings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFindingsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorServer).StreamFindings(m, &grpc.GenericServerStream[StreamFindingsRequest, Finding]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sensor_StreamFindingsServer = grpc.ServerStreamingServer[Finding]

func _Sensor_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sensor_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Sensor_ServiceDesc is the grpc.ServiceDesc for Sensor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sensor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videonode.control.Sensor",
	HandlerType: (*SensorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Sensor_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Sensor_Configure_Handler,
		},
		{
			MethodName: "AnalyzeOnce",
			Handler:    _Sensor_AnalyzeOnce_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Sensor_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFindings",
			Handler:       _Sensor_StreamFindings_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control/sensor.proto",
}
