// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: control/source.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Source_Describe_FullMethodName     = "/videonode.control.Source/Describe"
	Source_SetFormat_FullMethodName    = "/videonode.control.Source/SetFormat"
	Source_SetDevice_FullMethodName    = "/videonode.control.Source/SetDevice"
	Source_GetStatus_FullMethodName    = "/videonode.control.Source/GetStatus"
	Source_StreamStatus_FullMethodName = "/videonode.control.Source/StreamStatus"
	Source_Snapshot_FullMethodName     = "/videonode.control.Source/Snapshot"
	Source_Shutdown_FullMethodName     = "/videonode.control.Source/Shutdown"
)

// SourceClient is the client API for Source service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Source is the gRPC service exposed by every videonode-source binary
// over its per-instance Unix-domain socket (path passed via --grpc-listen).
// The daemon dials in, calls Describe() to record identity, then issues
// unary control RPCs and subscribes to StreamStatus for the unsolicited
// status push that replaces the legacy `status` JSON-RPC notification.
type SourceClient interface {
	// Describe returns the native binary's identity. First call after dial.
	Describe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NativeInfo, error)
	// SetFormat asks the source to reconfigure its V4L2 capture. The
	// `applied` bit reports whether the source actually re-armed (it may
	// refuse if the request matches the running format).
	SetFormat(ctx context.Context, in *SetFormatRequest, opts ...grpc.CallOption) (*SetFormatResponse, error)
	// SetDevice swaps the V4L2 device path the source captures from. Empty
	// path detaches and resumes placeholder broadcast. Same lock as
	// SetFormat; the orchestrator loop sees the new path on its next reinit
	// pass.
	SetDevice(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*SetDeviceResponse, error)
	// GetStatus returns the current status snapshot synchronously. Useful
	// for one-shot probes; the long-lived push is StreamStatus below.
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error)
	// StreamStatus yields Status frames on health change, consumer-count
	// change, or once per second as a heartbeat. The stream stays open
	// for the lifetime of the source process.
	StreamStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Status], error)
	// Snapshot captures one frame from the broadcast loop and returns the
	// raw NV12 plane bytes. Replaces the legacy daemon-as-dma-buf-consumer
	// path in internal/streams/snapshot_native.go — the daemon never opens
	// the SCM_RIGHTS data plane.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// Shutdown asks the source to exit cleanly.
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sourceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceClient(cc grpc.ClientConnInterface) SourceClient {
	return &sourceClient{cc}
}

func (c *sourceClient) Describe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NativeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NativeInfo)
	err := c.cc.Invoke(ctx, Source_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) SetFormat(ctx context.Context, in *SetFormatRequest, opts ...grpc.CallOption) (*SetFormatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFormatResponse)
	err := c.cc.Invoke(ctx, Source_SetFormat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) SetDevice(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*SetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDeviceResponse)
	err := c.cc.Invoke(ctx, Source_SetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Source_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) StreamStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Status], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Source_ServiceDesc.Streams[0], Source_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Status]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Source_StreamStatusClient = grpc.ServerStreamingClient[Status]

func (c *sourceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, Source_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Source_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServer is the server API for Source service.
// All implementations must embed UnimplementedSourceServer
// for forward compatibility.
//
// Source is the gRPC service exposed by every videonode-source binary
// over its per-instance Unix-domain socket (path passed via --grpc-listen).
// The daemon dials in, calls Describe() to record identity, then issues
// unary control RPCs and subscribes to StreamStatus for the unsolicited
// status push that replaces the legacy `status` JSON-RPC notification.
type SourceServer interface {
	// Describe returns the native binary's identity. First call after dial.
	Describe(context.Context, *emptypb.Empty) (*NativeInfo, error)
	// SetFormat asks the source to reconfigure its V4L2 capture. The
	// `applied` bit reports whether the source actually re-armed (it may
	// refuse if the request matches the running format).
	SetFormat(context.Context, *SetFormatRequest) (*SetFormatResponse, error)
	// SetDevice swaps the V4L2 device path the source captures from. Empty
	// path detaches and resumes placeholder broadcast. Same lock as
	// SetFormat; the orchestrator loop sees the new path on its next reinit
	// pass.
	SetDevice(context.Context, *SetDeviceRequest) (*SetDeviceResponse, error)
	// GetStatus returns the current status snapshot synchronously. Useful
	// for one-shot probes; the long-lived push is StreamStatus below.
	GetStatus(context.Context, *emptypb.Empty) (*Status, error)
	// StreamStatus yields Status frames on health change, consumer-count
	// change, or once per second as a heartbeat. The stream stays open
	// for the lifetime of the source process.
	StreamStatus(*emptypb.Empty, grpc.ServerStreamingServer[Status]) error
	// Snapshot captures one frame from the broadcast loop and returns the
	// raw NV12 plane bytes. Replaces the legacy daemon-as-dma-buf-consumer
	// path in internal/streams/snapshot_native.go — the daemon never opens
	// the SCM_RIGHTS data plane.
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// Shutdown asks the source to exit cleanly.
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedSourceServer()
}

// UnimplementedSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceServer struct{}

func (UnimplementedSourceServer) Describe(context.Context, *emptypb.Empty) (*NativeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedSourceServer) SetFormat(context.Context, *SetFormatRequest) (*SetFormatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFormat not implemented")
}
func (UnimplementedSourceServer) SetDevice(context.Context, *SetDeviceRequest) (*SetDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDevice not implemented")
}
func (UnimplementedSourceServer) GetStatus(context.Context, *emptypb.Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSourceServer) StreamStatus(*emptypb.Empty, grpc.ServerStreamingServer[Status]) error {
	return status.Error(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedSourceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedSourceServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedSourceServer) mustEmbedUnimplementedSourceServer() {}
func (UnimplementedSourceServer) testEmbeddedByValue()                {}

// UnsafeSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServer will
// result in compilation errors.
type UnsafeSourceServer interface {
	mustEmbedUnimplementedSourceServer()
}

func RegisterSourceServer(s grpc.ServiceRegistrar, srv SourceServer) {
	// If the following call panics, it indicates UnimplementedSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Source_ServiceDesc, srv)
}

func _Source_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).Describe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_SetFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFormatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).SetFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_SetFormat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).SetFormat(ctx, req.(*SetFormatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_SetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).SetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_SetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).SetDevice(ctx, req.(*SetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceServer).StreamStatus(m, &grpc.GenericServerStream[emptypb.Empty, Status]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Source_StreamStatusServer = grpc.ServerStreamingServer[Status]

func _Source_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Source_ServiceDesc is the grpc.ServiceDesc for Source service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Source_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videonode.control.Source",
	HandlerType: (*SourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Source_Describe_Handler,
		},
		{
			MethodName: "SetFormat",
			Handler:    _Source_SetFormat_Handler,
		},
		{
			MethodName: "SetDevice",
			Handler:    _Source_SetDevice_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Source_GetStatus_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Source_Snapshot_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Source_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _Source_StreamStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control/source.proto",
}
