// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: control/source.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetFormatRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Fourcc string                 `protobuf:"bytes,1,opt,name=fourcc,proto3" json:"fourcc,omitempty"`
	W      uint32                 `protobuf:"varint,2,opt,name=w,proto3" json:"w,omitempty"`
	H      uint32                 `protobuf:"varint,3,opt,name=h,proto3" json:"h,omitempty"`
	// 0 = "driver decides"
	Fps           uint32 `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFormatRequest) Reset() {
	*x = SetFormatRequest{}
	mi := &file_control_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFormatRequest) ProtoMessage() {}

func (x *SetFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFormatRequest.ProtoReflect.Descriptor instead.
func (*SetFormatRequest) Descriptor() ([]byte, []int) {
	return file_control_source_proto_rawDescGZIP(), []int{0}
}

func (x *SetFormatRequest) GetFourcc() string {
	if x != nil {
		return x.Fourcc
	}
	return ""
}

func (x *SetFormatRequest) GetW() uint32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *SetFormatRequest) GetH() uint32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *SetFormatRequest) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

type SetFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFormatResponse) Reset() {
	*x = SetFormatResponse{}
	mi := &file_control_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFormatResponse) ProtoMessage() {}

func (x *SetFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFormatResponse.ProtoReflect.Descriptor instead.
func (*SetFormatResponse) Descriptor() ([]byte, []int) {
	return file_control_source_proto_rawDescGZIP(), []int{1}
}

func (x *SetFormatResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_control_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_control_source_proto_rawDescGZIP(), []int{2}
}

type SnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw NV12 planes copied out of the most-recent dma-buf. The daemon's
	// existing ffmpeg subprocess encodes JPEG from these — same pipeline
	// shape as the legacy snapshot_native.go, just over gRPC.
	Nv12     []byte `protobuf:"bytes,1,opt,name=nv12,proto3" json:"nv12,omitempty"`
	Width    uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height   uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	PitchY   uint32 `protobuf:"varint,4,opt,name=pitch_y,json=pitchY,proto3" json:"pitch_y,omitempty"`
	PitchUv  uint32 `protobuf:"varint,5,opt,name=pitch_uv,json=pitchUv,proto3" json:"pitch_uv,omitempty"`
	FrameIdx uint64 `protobuf:"varint,6,opt,name=frame_idx,json=frameIdx,proto3" json:"frame_idx,omitempty"`
	// CLOCK_MONOTONIC nanoseconds at the moment Snapshot grabbed the frame.
	CapturedAtNs  uint64 `protobuf:"varint,7,opt,name=captured_at_ns,json=capturedAtNs,proto3" json:"captured_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_control_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_control_source_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotResponse) GetNv12() []byte {
	if x != nil {
		return x.Nv12
	}
	return nil
}

func (x *SnapshotResponse) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SnapshotResponse) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SnapshotResponse) GetPitchY() uint32 {
	if x != nil {
		return x.PitchY
	}
	return 0
}

func (x *SnapshotResponse) GetPitchUv() uint32 {
	if x != nil {
		return x.PitchUv
	}
	return 0
}

func (x *SnapshotResponse) GetFrameIdx() uint64 {
	if x != nil {
		return x.FrameIdx
	}
	return 0
}

func (x *SnapshotResponse) GetCapturedAtNs() uint64 {
	if x != nil {
		return x.CapturedAtNs
	}
	return 0
}

var File_control_source_proto protoreflect.FileDescriptor

const file_control_source_proto_rawDesc = "" +
	"\n" +
	"\x14control/source.proto\x12\x11videonode.control\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14control/common.proto\"X\n" +
	"\x10SetFormatRequest\x12\x16\n" +
	"\x06fourcc\x18\x01 \x01(\tR\x06fourcc\x12\f\n" +
	"\x01w\x18\x02 \x01(\rR\x01w\x12\f\n" +
	"\x01h\x18\x03 \x01(\rR\x01h\x12\x10\n" +
	"\x03fps\x18\x04 \x01(\rR\x03fps\"-\n" +
	"\x11SetFormatResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\"\x11\n" +
	"\x0fSnapshotRequest\"\xcb\x01\n" +
	"\x10SnapshotResponse\x12\x12\n" +
	"\x04nv12\x18\x01 \x01(\fR\x04nv12\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x17\n" +
	"\apitch_y\x18\x04 \x01(\rR\x06pitchY\x12\x19\n" +
	"\bpitch_uv\x18\x05 \x01(\rR\apitchUv\x12\x1b\n" +
	"\tframe_idx\x18\x06 \x01(\x04R\bframeIdx\x12$\n" +
	"\x0ecaptured_at_ns\x18\a \x01(\x04R\fcapturedAtNs2\xb9\x03\n" +
	"\x06Source\x12A\n" +
	"\bDescribe\x12\x16.google.protobuf.Empty\x1a\x1d.videonode.control.NativeInfo\x12V\n" +
	"\tSetFormat\x12#.videonode.control.SetFormatRequest\x1a$.videonode.control.SetFormatResponse\x12>\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x19.videonode.control.Status\x12C\n" +
	"\fStreamStatus\x12\x16.google.protobuf.Empty\x1a\x19.videonode.control.Status0\x01\x12S\n" +
	"\bSnapshot\x12\".videonode.control.SnapshotRequest\x1a#.videonode.control.SnapshotResponse\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBIZGgithub.com/smazurov/videonode/internal/streams/pipelinectl/pb;controlpbb\x06proto3"

var (
	file_control_source_proto_rawDescOnce sync.Once
	file_control_source_proto_rawDescData []byte
)

func file_control_source_proto_rawDescGZIP() []byte {
	file_control_source_proto_rawDescOnce.Do(func() {
		file_control_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_source_proto_rawDesc), len(file_control_source_proto_rawDesc)))
	})
	return file_control_source_proto_rawDescData
}

var file_control_source_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_control_source_proto_goTypes = []any{
	(*SetFormatRequest)(nil),  // 0: videonode.control.SetFormatRequest
	(*SetFormatResponse)(nil), // 1: videonode.control.SetFormatResponse
	(*SnapshotRequest)(nil),   // 2: videonode.control.SnapshotRequest
	(*SnapshotResponse)(nil),  // 3: videonode.control.SnapshotResponse
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
	(*NativeInfo)(nil),        // 5: videonode.control.NativeInfo
	(*Status)(nil),            // 6: videonode.control.Status
}
var file_control_source_proto_depIdxs = []int32{
	4, // 0: videonode.control.Source.Describe:input_type -> google.protobuf.Empty
	0, // 1: videonode.control.Source.SetFormat:input_type -> videonode.control.SetFormatRequest
	4, // 2: videonode.control.Source.GetStatus:input_type -> google.protobuf.Empty
	4, // 3: videonode.control.Source.StreamStatus:input_type -> google.protobuf.Empty
	2, // 4: videonode.control.Source.Snapshot:input_type -> videonode.control.SnapshotRequest
	4, // 5: videonode.control.Source.Shutdown:input_type -> google.protobuf.Empty
	5, // 6: videonode.control.Source.Describe:output_type -> videonode.control.NativeInfo
	1, // 7: videonode.control.Source.SetFormat:output_type -> videonode.control.SetFormatResponse
	6, // 8: videonode.control.Source.GetStatus:output_type -> videonode.control.Status
	6, // 9: videonode.control.Source.StreamStatus:output_type -> videonode.control.Status
	3, // 10: videonode.control.Source.Snapshot:output_type -> videonode.control.SnapshotResponse
	4, // 11: videonode.control.Source.Shutdown:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_source_proto_init() }
func file_control_source_proto_init() {
	if File_control_source_proto != nil {
		return
	}
	file_control_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_source_proto_rawDesc), len(file_control_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_source_proto_goTypes,
		DependencyIndexes: file_control_source_proto_depIdxs,
		MessageInfos:      file_control_source_proto_msgTypes,
	}.Build()
	File_control_source_proto = out.File
	file_control_source_proto_goTypes = nil
	file_control_source_proto_depIdxs = nil
}
