import { defineConfig } from 'vitepress';
import { withMermaid } from 'vitepress-plugin-mermaid';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// docs/.vitepress/version.json is generated by chglog at predev/prebuild
// (see package.json scripts). Default to 'dev' if missing.
const versionPath = resolve(process.cwd(), 'docs/.vitepress/version.json');
const version = existsSync(versionPath)
  ? (JSON.parse(readFileSync(versionPath, 'utf8')).version ?? 'dev')
  : 'dev';

export default withMermaid(
  defineConfig({
    title: 'VideoNode',
    description: 'A hardware-accelerated video streaming daemon for Linux.',
    base: '/videonode/',
    cleanUrls: true,
    lastUpdated: true,
    ignoreDeadLinks: [/^http:\/\/localhost/],

    head: [
      ['link', { rel: 'icon', href: '/videonode/favicon.ico' }],
    ],

    themeConfig: {
      nav: [
        { text: 'Docs', link: '/getting-started/introduction' },
        {
          text: `v${version}`,
          items: [
            { text: 'Changelog', link: '/changelog' },
            { text: 'Releases on GitHub', link: 'https://github.com/smazurov/videonode/releases' },
          ],
        },
        { text: 'GitHub', link: 'https://github.com/smazurov/videonode' },
      ],

      sidebar: [
        {
          text: 'Getting Started',
          collapsed: false,
          items: [
            { text: 'Introduction', link: '/getting-started/introduction' },
            { text: 'Installation', link: '/getting-started/installation' },
            { text: 'Quickstart', link: '/getting-started/quickstart' },
          ],
        },
        {
          text: 'Reference',
          collapsed: false,
          items: [
            { text: 'Supported hardware', link: '/reference/supported-hardware' },
            { text: 'config.toml', link: '/reference/config-toml' },
            { text: 'Pipeline model', link: '/reference/pipeline-model' },
            { text: 'REST API', link: '/reference/rest-api' },
          ],
        },
        {
          text: 'Operating',
          collapsed: false,
          items: [
            { text: 'Streaming outputs', link: '/operating/streaming-outputs' },
            { text: 'Encoders', link: '/operating/encoders' },
            { text: 'Observability', link: '/operating/observability' },
          ],
        },
        {
          text: 'Development',
          collapsed: false,
          items: [
            { text: 'Architecture', link: '/development/architecture' },
            { text: 'Source & formats', link: '/development/source-and-formats' },
            { text: 'Events & SSE', link: '/development/events-and-sse' },
            { text: 'Building from source', link: '/development/building' },
          ],
        },
      ],

      search: {
        provider: 'local',
      },

      socialLinks: [
        { icon: 'github', link: 'https://github.com/smazurov/videonode' },
      ],

      editLink: {
        pattern: 'https://github.com/smazurov/videonode/edit/main/website/docs/:path',
        text: 'Edit this page on GitHub',
      },

      footer: {
        message: 'Released under the <a href="https://github.com/smazurov/videonode/blob/main/LICENSE">AGPL-3.0 License</a>.',
        copyright: `Copyright © ${new Date().getFullYear()} Stepan Mazurov`,
      },
    },

    mermaid: {
      flowchart: { useMaxWidth: true, htmlLabels: true, curve: 'basis' },
    },
  })
);
