name: CI - Docs

on:
  pull_request:
    paths:
      - 'website/**'
      - '.github/workflows/ci-docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: pnpm/action-setup@v6
        with:
          package_json_file: website/package.json
      - name: Install
        working-directory: website
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: website
        run: pnpm build
